### ISSUE TITLE
GameLauncher 2.0.2.2 LZMA.ddl Missing

### ISSUE THREAD

**Issue by DavidCarbon** [SoapboxRaceWorld/GameLauncher_NFSW#1]
- **Launcher Version:** 2.0.2.2
- **Operating system:** Windows Ten
- **Antivirus/Firewall (if any):** Virus are good too... not really I got fu*ked once and system 32 was nuked.

You did it again :( 
WHYY!!
LZMA.ddl is missing

**Comment by DavidCarbon** [comment]
Also
Welcome Back, LoL

**Comment by DavidCarbon** [comment]
Just add LZMA to Release instead of making a new release 🤔

**Comment by ghost** [comment]
Added under new ZIP file name.
