### ISSUE TITLE
With a custom build, download full game launcher was crash.

### ISSUE THREAD

**Issue by Mellowz** [SoapboxRaceWorld/GameLauncher_NFSW#100]
- **Launcher Version:** 2.0.0.15
- **Operating system:** Windows10
- **Antivirus/Firewall (if any):** -
- **Wine/Mono Version (if any):** -

![1542117699988](https://user-images.githubusercontent.com/139546/48418242-5d7eea80-e787-11e8-9273-e14583a00b24.jpg)

this happen when i try to force launcher create folder GameFiles in current directory.

**Comment by metonator** [comment]
You tried to compile x64 version of launcher. LZMA.dll is x86 therefore it will fail with x64, try compiling it on "Release" and "x86"

**Comment by Mellowz** [comment]
> You tried to compile x64 version of launcher. LZMA.dll is x86 therefore it will fail with x64, try compiling it on "Release" and "x86"

Ok, now it's work, only for x86 LZMA.dll support ?, any way thank you so much.

**Comment by metonator** [comment]
Yea, this file is taken directly from EA Original Launcher, we could also replace it with our own x64_86 build, but SpeedLoad is not yet done.
