### ISSUE TITLE
Can't Play The Game

### ISSUE THREAD

**Issue by mrbarrel** [SoapboxRaceWorld/GameLauncher_NFSW#100]
![Screenshot 2020-10-19 171517](https://user-images.githubusercontent.com/73108616/96436224-1aa9d500-1230-11eb-8f12-6526bfc05103.png)

![Screenshot 2020-10-19 172054](https://user-images.githubusercontent.com/73108616/96436322-21384c80-1230-11eb-9e50-7c0e519edbc4.png)

did i something wrong?

- **Launcher Version: v2.1.6.2 
- **Operating system: Windows 10
- **Antivirus/Firewall (if any): From Windows is self
- **Wine/Mono Version (if any): -

**Comment by l0rdkai** [comment]
same here please help

**Comment by xxpiter** [comment]
same here please help

**Comment by xxpiter** [comment]
a few minutes of play and ...
![127](https://user-images.githubusercontent.com/73783962/98854017-4ba9ae00-245a-11eb-847a-105d3c85d13d.JPG)

**Comment by Reinald268** [comment]
I had the same problem i just deleted all the game files and downloaded it all over again. I was extra carefull not to make any mistakes while downloading the files and do them all on first try. After that it was all good.
