### ISSUE TITLE
Problem installing the game

### ISSUE THREAD

**Issue by xxpiter** [SoapboxRaceWorld/GameLauncher_NFSW#103]
- **Launcher Version:** v2.1.6.4
- **Operating system:** Windows 10 64 Bit
- **Antivirus/Firewall (if any):** Norton Internet Security
- **Wine/Mono Version (if any):** 

![123](https://user-images.githubusercontent.com/73783962/97804811-83db1080-1c52-11eb-8c60-738b025be4ca.JPG)
![124](https://user-images.githubusercontent.com/73783962/97804824-948b8680-1c52-11eb-9c17-0d2d3aa81534.JPG)

Despite completely uninstalling the antivirus, the launcher refuses to download the game files. How to fix it?

**Comment by DavidCarbon** [comment]
You need to switch CDNs in the Gear Icon. The three CDNs that are online is DavidCarbon and NightRiderz.

**Comment by xxpiter** [comment]
Why can't I use the WorldUnited.gg network
![125](https://user-images.githubusercontent.com/73783962/97857907-af1b3980-1cfe-11eb-8575-6913f11f42f7.JPG)

**Comment by xxpiter** [comment]
It's ok. After setting the alternative network, and after saving the settings, quit GameLauncher and restart.
![126](https://user-images.githubusercontent.com/73783962/97873850-79834a00-1d18-11eb-9ac1-ea502fc37b49.JPG)
After restarting the WorldUnited.gg network it set itself up. And it all started working fine.
