### ISSUE TITLE
Game starts in the background

### ISSUE THREAD

**Issue by Hoerli1337** [SoapboxRaceWorld/GameLauncher_NFSW#106]
- **Launcher Version: 2.1.6.4** 
- **Operating system: Windows 10 Pro** 
- **Antivirus/Firewall (if any): Windows Defender / Windows Firewall** 
- **Resolution: 2560x1440p @ 144Hz** 

The game starts in the background and cannot be opened.
After login, the game will start. I hear the sound of the intro, but I cannot switch to the game.
It is only available in the taskbar.
When I click on it, Windows tries to open the game, the screen turns black for a moment and ... zack the game is minimized again.

I only have this problem with my AMD Radeon RX 5700XT.
Formerly with two nVidia GeForce GTX 980 or currently with my notebook and a GeForce 1070, it runs without problems.

In a virtual machine running VMware, it works fine. But I don't feel like playing the whole thing in a VM.
If I could get the game in windowed mode, I might have a chance to play it.

**Comment by ThaThing** [comment]
I found a workaround for this issue.

Go to %appdata%\Need for Speed World\Settings
Edit the UserSettings.xml

Go to the bottom and find the following lines: 
```
        <screenheight Type="int">768</screenheight>
        <screenwidth Type="int">1024</screenwidth>
        <screenwindowed Type="int">0</screenwindowed>
```

and update them to your screen resolution and change the 0 to 1:
```
        <screenheight Type="int">1920</screenheight>
        <screenwidth Type="int">1080</screenwidth>
        <screenwindowed Type="int">1</screenwindowed>
```

Save the file, and open the launcher. That made me able to play the game with this issue.
