### ISSUE TITLE
Error in GameLauncher _Installer

### ISSUE THREAD

**Issue by 1DavidCarbon** [SoapboxRaceWorld/GameLauncher_NFSW#109]
- **Launcher Version:** 2.0.0.15 (Current Installer Release)
Newtonsoft.Json.dll file missing from this installer build [1.9.57]. New release build [1.9.58] has fixed this issue.

**Comment by 1DavidCarbon** [comment]
Fixed Thanks @metonator

**Comment by metonator** [comment]
Updated installer.
