### ISSUE TITLE
LZMA.dll

### ISSUE THREAD

**Issue by SpiritLeRenard** [SoapboxRaceWorld/GameLauncher_NFSW#112]
I just downloaded the launcher, while launching it, it said it's downloading LZMA.dll then said I must restart the launcher. And when I restart it, it says the file LZMA.dll is invalid

**Comment by mionelinho** [comment]
I got same, someone can help?

**Comment by ask-05** [comment]
> I got same, someone can help?



> I just downloaded the launcher, while launching it, it said it's downloading LZMA.dll then said I must restart the launcher. And when I restart it, it says the file LZMA.dll is invalid


Guys, download the previous version. It fixed the lzma.dll issue.

**Comment by SpiritLeRenard** [comment]
Problem is, the previous version give me the server infinite loading bug

**Comment by x-Ghosts** [comment]
> I just downloaded the launcher, while launching it, it said it's downloading LZMA.dll then said I must restart the launcher. And when I restart it, it says the file LZMA.dll is invalid

Hello @SonEfAdam @mionelinho @SpiritLeRenard !

Use the latest launcher version, it fixes all missing files on your Launcher Files folder.

Make sure, you delete first of all the files of your Launcher Files, and it should not be mixed with the Gamefiles.
Extract the zip files from the Release.zip to the following directory (Make sure you create a folder on C named by SBRW) : C:\SBRW\Launcher Files or C:\SoapBox Race World\Launcher Files - check the image https://imgur.com/a/mXgccEu.

**Comment by x-Ghosts** [comment]
> Problem is, the previous version give me the server infinite loading bug

Hello @SpiritLeRenard !

This issue of infinite loading is a server issue, not caused by the Launcher. 
The launcher role, is only to launch your game, that's it.

**Comment by MrEliteTM** [comment]
> > I just downloaded the launcher, while launching it, it said it's downloading LZMA.dll then said I must restart the launcher. And when I restart it, it says the file LZMA.dll is invalid
> 
> Hello @SonEfAdam @mionelinho @SpiritLeRenard !

Use the latest launcher version, it fixes all missing files on your **Launcher Files folder**.
> 
> Make sure, you delete first of all the files of your Launcher Files, and it **should not be mixed with the Gamefiles**.
> Extract the zip files from the **Release.zip** to the following directory (Make sure you create a folder on C named by SBRW) : **C:\SBRW\Launcher Files** or **C:\SoapBox Race World\Launcher Files** - check the image **https://imgur.com/a/mXgccEu**.
