### ISSUE TITLE
Can't see any players

### ISSUE THREAD

**Issue by whazxc** [SoapboxRaceWorld/GameLauncher_NFSW#115]
Can not see any players on the map and when i try to teleport to someone i do not see him aswell (he can not see me too). I tried inviting a friend in party and start private race but It doesnt put me in the race, only puts him in it. So neither friends nor randoms can see me and i cant see them.

**Comment by Nevada789** [comment]
Serverside issue, you need to contact the server you're connected to via their discord's support channel.
