### ISSUE TITLE
WorldUnited.gg Server Mod files very slow download

### ISSUE THREAD

**Issue by ghost** [SoapboxRaceWorld/GameLauncher_NFSW#116]
**Launcher Version:** 
  2.1.6.6
 **Operating system:** 
 Windows 10
 **Antivirus/Firewall (if any):** 
 Avast Anti-Virus

Issue description:
NFS World main game downloads fine but WorldUnited.gg downloads at a very slow rate.. Once 30MB to 50MB has been downloaded, the download would be disrupted by the game saying that it has a Data Error.. Once you click ok on the Data Error pop-up, the launcher would have another pop-up saying "ModNet: An Unhandled Exception Appeared"... I tried getting help but none of the solutions work.. I disabled the antivirus.. I downloaded the game on a separate folder, but nothing.. The issue persists..

**Comment by Nevada789** [comment]
Serverside issue, user already contacted support on said server.
