### ISSUE TITLE
Launcher not open

### ISSUE THREAD

**Issue by bomble12456** [SoapboxRaceWorld/GameLauncher_NFSW#118]
- **Launcher Version: 2.1.7.1
- **Operating system: win.8.1 
- **Antivirus/Firewall (if any): Windows defender 
- **Wine/Mono Version (if any):**

**Comment by maxside2** [comment]
AYUDA ME SALIO ESTO CON LA RECIENTE ACTUALIZACION

ELIJA UN DIRECTORIO DIFERENTE PARA EL LANZADOR DEL JUEGO.
CARPETAS ESPECIALES COMO:
DESCARGAS DOCUMENTOS VÍDEOS DE ESCRITORIO MÚSICA ONEDRIVE O CUALQUIER TIPO DE CARPETAS DE USUARIO
SE DESACTIVAN

**Comment by bomble12456** [comment]
thanks for your help @maxside2
