### ISSUE TITLE
download exception

### ISSUE THREAD

**Issue by confite276** [SoapboxRaceWorld/GameLauncher_NFSW#123]
download exception : system.IOException: The Process cannot access 
the file C:\Soapbox Race World|Need For Speed World\CARS\BMW135I08\GEOMETRY.bin
because it is being used by another proccess
at System.IO.__Error.WinIOError(Int32 errorCode,string maybeFullPatch)
at System.IO.FileStream-Init(String path, FileMode modo,FileAccess access,Int32 rights,Boolean useRights,File share
share ,Int32 bufferSize,FileOptions options,SECURITY_ATTRIBUTES secAttrs,String 
checkHost)
at System.IO.FileStream..ctor (String path, FileMode mode,fileaccess
access,FileShare share,INT32 buffersize)
at System.IO.File.Create(String path,Int32 bufferSize)
at GameLauncher.Downloader.Download(Object parameters) 

PD: That is the error that I get, then it tells me to change the CDN (previously done, if I manage to install it, I delete the complaint, thanks <3)

**Comment by x-Ghosts** [comment]
Hello @confite276 !

Try to download manually the gamefiles, via this link. 
Link for the download : **https://drive.google.com/file/d/1RIc7UCza2CsRCnqvsg_JcG7kY-EBqdZA**

Once the process of the gamefiles download is done, extract the Zip files on the GameFiles folder, and overwrite the content of it (if some files already existed, make sure you overwrite them). 

This should be actual solution of your issue. 
Inform me if the issue has been fixed


Kind Regards,
Mr.Elite
