### ISSUE TITLE
Game files broken after updated new nfsw launcher.

### ISSUE THREAD

**Issue by ken640** [SoapboxRaceWorld/GameLauncher_NFSW#127]
- **Launcher Version:** 
- **Operating system:** 
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):**

**Comment by x-Ghosts** [comment]
Hello @ken640 !

Can you explain or porivde more the info's with an attached screenshot that shows the issue. Because the **Game Files broken after updated new nfsw launcher** is a wide support question.

You can always answer bellow my message here.
Kind Regards,
Mr.Elite
