### ISSUE TITLE
Can find and play with other players

### ISSUE THREAD

**Issue by AlexSeab** [SoapboxRaceWorld/GameLauncher_NFSW#13]
- **Launcher Version:** 
- **Operating system:** 
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 

Hi, im with the las version and i cant find anyone on the map and cant run in multiplayer neither.
But i can chat with others.

**Comment by ghost** [comment]
This was caused by missing lightfx.dll installation. This has been fixed on latest release launcher.
