### ISSUE TITLE
decompression returned 1

### ISSUE THREAD

**Issue by davibr1** [SoapboxRaceWorld/GameLauncher_NFSW#131]
- **Launcher Version:** 2.1.7.2
- **Operating system:** windows 10
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 

I'm trying to install the game but this error always happens, I've tried all the cdn's in the launcher but none work and this error still persists, what should I do?

**Comment by x-Ghosts** [comment]
Hello @davibr1 ! 

Try to manually download the gamefiles from this Zip file : https://drive.google.com/file/d/1RIc7UCza2CsRCnqvsg_JcG7kY-EBqdZA

Once you have downloaded this, go on your main drive where the OS hard drive exist : 

**This Pc -> Disk Local (C:)**, and create a new folder there, name it by **SBRW Gamefiles**. Extract the gamefiles that you have just download it on that folder **SBRW Gamefiles**
