### ISSUE TITLE
"Don't found Geometry.bin."

### ISSUE THREAD

**Issue by JGTG7** [SoapboxRaceWorld/GameLauncher_NFSW#132]
- **Launcher Version:**  2.1.7.2
- **Operating system:** Windows 64bits.

When I try to start the game I get this error,the problem comes from the ".data" folder with "Geometry.bin" file. Investigate and the program automatically renames that file to "Geometry.bin.orig" which makes it impossible to start the game.This problem comes from the Mods,(it happens on all servers,but with different files)
![IMG_20210222_010824172](https://user-images.githubusercontent.com/79481881/108770992-9d190d00-7520-11eb-9c14-dc03421111d4.jpg)

**Comment by JGTG7** [comment]
The problem persists.

**Comment by x-Ghosts** [comment]
Hello @JGTG7 !

It's recommended to make first of all the gamefiles installation via this Game Directory : **C:\SBRW**

Question : Why I don't find on **C:\** the folder **SBRW**? 
=> In this case, you must create a folder named by SBRW, and in this folder create two more folders, one for the Gamefiles, and one for the Launcher files. Please check this image to see the result of how the installation process should be : **https://imgur.com/a/mXgccEu**.

I recommend a fresh Gamefiles and Launcher files installation in this case. 
=> Get the launcher files updated via this link : **https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/releases/download/2.1.7.3/Release_2.1.7.3.zip**

Kind Regard,
- Neroh
