### ISSUE TITLE
Moving to any folder, have the same error.

### ISSUE THREAD

**Issue by zurabi97** [SoapboxRaceWorld/GameLauncher_NFSW#138]
- **Launcher Version:** 
- 2.1.7.6
- **Operating system:** 
- Windows 10 20H2
- **Antivirus/Firewall (if any):** 
- MS Defender
- **Wine/Mono Version (if any):** 
- -

Moving the GameLauncher files to any folder, and the error pops up:
![SharedScreenshot](https://user-images.githubusercontent.com/29329067/109413711-72fb9b00-79b7-11eb-9be5-ea87572a3a7d.jpg)

**Comment by DavidCarbon** [comment]
Launcher folder and Game files should be moved at the root of the Drive (Within a folder at the root folder)
 Example:
 C:\Soapbox Race World\Launcher
  C:\Soapbox Race World\Game Files

**Comment by Hanol48** [comment]
Habe selbes Problem!!!! Habe echtes Geld gespendet in den Server und erwarte Hilfe!

**Comment by zurabi97** [comment]
> Launcher folder and Game files should be moved at the root of the Drive (Within a folder at the root folder)
> Example:
> C:\Soapbox Race World\Launcher
> C:\Soapbox Race World\Game Files

Thank you, it worked.
