### ISSUE TITLE
There was an error while downloading ModNet files: "The remote server returned an error: (404) Not Found." [bug] [Linux]

### ISSUE THREAD

**Issue by Airo675** [SoapboxRaceWorld/GameLauncher_NFSW#140]
- **Launcher Version:** 2.1.6.5
- **Operating system:** Linux Pop!_OS (Debian)
- **Antivirus/Firewall (if any):** Lol no
- **Wine/Mono Version (if any):** Pretty sure its Wine 6, Idk which Mono
- Downloaded it from Lutris
- Error appears every time while clicking "Play Now"
- it says Fetching Modnetreloaded files: Dinput8.ddl
- Appears every time on every server
- https://i.imgur.com/Lu1a9qQ.png

**Comment by Zacam** [comment]
You need to replace the Lutris default package version with the GitHub Release version (and include the contents of the _LinuxCompat.zip archive as well)
