### ISSUE TITLE
Game Launcher Game Downloader (Missing LZMA File) 2.0.0.20

### ISSUE THREAD

**Issue by 1DavidCarbon** [SoapboxRaceWorld/GameLauncher_NFSW#141]
- **Launcher Version:** 2.0.0.20
- **Operating system:** Windows 10 Home
```
You forgot to include LZMA DDL file. Existing users might not see 
this issue but a complete fresh install will cause this error.
```
![Image of Launcher](https://davidcarbon.ml/wp-content/uploads/2018/12/Missing-DDL-LZMA.png)
![Image of Launcher](https://davidcarbon.ml/wp-content/uploads/2018/12/Missing-DDL-LZMA-3.png)
![Image of Launcher](https://davidcarbon.ml/wp-content/uploads/2018/12/Missing-DDL-LZMA-4.png)
![Image of Launcher](https://davidcarbon.ml/wp-content/uploads/2018/12/Missing-DDL-LZMA-2.png)

**Comment by metonator** [comment]
ZIP Updated.
