### ISSUE TITLE
Access Problem Game Launcher 2.0.0.20

### ISSUE THREAD

**Issue by saldatura** [SoapboxRaceWorld/GameLauncher_NFSW#142]
Hi guys,
I have this problem with Game Launcher: Game Crash: Access Violation (0xC0000005) and when I click "Enter World" the game goes to Crash 

![annotazione 2018-12-15 233337](https://user-images.githubusercontent.com/45906037/50050573-6274e800-00ff-11e9-9ea4-f61766ae445d.jpg)

Best reguards

**Comment by saldatura** [comment]
I upgrade game launcher with 2.0.1.0 but I have same problem

**Comment by Nevada789** [comment]
try disabling ModNet in the launcher settings

**Comment by metonator** [comment]
Nevada on github :o

**Comment by Nevada789** [comment]
i've always been here lmao
since like 2015

**Comment by metonator** [comment]
Thats 2 years later after networking Kappa

**Comment by metonator** [comment]
ahead*

**Comment by Nevada789** [comment]
well... i guess it's time to get schooled by some nerd with a 2006 dual core xeon who thinks low latency fixes everything, or how about the dude who thought the fact he worked for a phone company meant he could solve MP being down by upgrading the network

**Comment by saldatura** [comment]
Thanks to everyone, unfortunately the problem is not solved

**Comment by metonator** [comment]
Because you probably try to inject something that is not compatible with game, or game folder doesnt have all required files.
