### ISSUE TITLE
Linha de código de parâmetros com erro. como arrumar?

### ISSUE THREAD

**Issue by Ramonfc46** [SoapboxRaceWorld/GameLauncher_NFSW#143]
- **Launcher Version:2.1.7.6** 
- **Operating system: windows 10** 
- **Antivirus/Firewall (if any) avast:** 
- **Wine/Mono Version (if any):** 

mensagem que aparece do erro; Game was Launched  with invalid command line  parameters ( You problably intended to run the launcher.)

Por favor , como faço para arrumar esse erro ? 
att: Ramon AFC

**Comment by Samueul** [comment]
Estou com o mesmo problema se conseguir resolver me chama no discord prf $amuel#3888
