### ISSUE TITLE
Gamelauncher 2.0.10 

### ISSUE THREAD

**Issue by olli203** [SoapboxRaceWorld/GameLauncher_NFSW#143]
2.0.0.10
W10
Enabled both
I cant launch with the new update, i did fresh install of the game because new update, The New welcome screen i put download size standard and location to folder on desctop. Then i press Gamelauncher to launch it i wait and wait nothing happens then i go taskbar see the game icon and right way it goes awaY. computer reboot doesnt work, What do i need to do to fix this? Please if i lose my 152  day diamond streak can u someway return it? Please help and thanks

**Comment by MrLigo** [comment]
same problem for me

**Comment by Dyn4mus** [comment]
I was updating the gamelauncher, but when i updated it, i opened the gamelauncher and i was waiting...waiting........waiting and nothing happens. i was thinking that is just bug. then i re-opened back the game launcher and nothing happens again. So i tried restart the PC and try to run the gamelauncher, but the same thing. I Also deleted the game and re-installed back, but when i was installing again , nothings happens AGAIN!!!

pls soapbox, fix that annoying thing!

**Comment by olli203** [comment]
Dyn4mus ik the feelin. I hope they fix it and they can return my daily gem progress

**Comment by nex0official** [comment]
Install older version and wait for fix: https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/releases/tag/2.0.0.20

**Comment by metonator** [comment]
I can claim that everyone that plays on WOPL will get its TH restored.
