### ISSUE TITLE
Linux: login/register fails with "Failed to get reply from server. Please retry."

### ISSUE THREAD

**Issue by ConstBur** [SoapboxRaceWorld/GameLauncher_NFSW#145]
- **Launcher Version:** 2.1.7.6 with LinuxCompat applied
- **Operating system:** Linux Manjaro KDE
- **Antivirus/Firewall (if any):** none
- **Wine/Mono Version (if any):** Wine 6.3, Mono 6.0.0 (also tried lutris-nfsworld-5.4 Wine version, Mono 4.9.4)

Occurs on vanilla install of the launcher with Linux dlls added. 
No matter which server I choose, a window with the message "Failed to get reply from server. Please retry." appears when trying to register/login (see screenshot below).
No output is produced in the terminal and no fail/error message appears in logs.
Also tried disabling the proxy, same result.

![image](https://user-images.githubusercontent.com/29761079/111058229-f955b980-845a-11eb-9ab5-4d25a69ff693.png)

**Comment by Techcrafter** [comment]
I have noticed the same issue!
I tried on multiple servers, but the login always seems to fail!

6 days ago the login worked perfectly fine without any problems.

**Comment by Techcrafter** [comment]
@ConstBur
I have found a workaround for this problem!

1. Delete all game files and folders if there are any.
2. Create the following folder structure on your default wineprefix C:
    `C:\Programs\Soapbox Race World\GameFiles`
3. Extract the release and linux-comapt.zip in the Soapbox Race World folder and launch GameLauncher.exe by double-clicking it.
4. Wait until it crashes and modify settings.ini to match the correct settings:
    [GameLauncher]
InstallationDirectory = C:\Programs\Soapbox Race World\GameFiles
CDN = https://cdn.worldunited.gg
Language = EN
DisableProxy = 0
DisableRPC = 0
IgnoreUpdateVersion = 
GameIntegrity = Good
ProxyPort = 

5. Start the launcher again and wait for the download to complete. After the download completed, close the window.
6. Install winetricks if you haven't already `sudo apt install winetricks`.
7. Open wintricks and create a new wineprefix with 64-bit architecture and the name `SoapboxRaceWorld`.
8. Create the following folder structure inside your NEW wineprefix C: (this should be located at /home/USERNAME/.local/share/wineprefixes/SoapboxRaceWorld/drive_c)
    `C:\Programs\Soapbox Race World`
9. Cut the GameFiles folder from your default wineprefix and paste it into the new Soapbox Race World folder you've just created.
10. Open a terminal in your DEFAULT wineprefix C:\Programs\Soapbox Race World folder and run the following command (replace USERNAME with your username):
     `WINEPREFIX=/home/USERNAME/.local/share/wineprefixes/SoapboxRaceWorld wine GameLauncher.exe`

**You should now be able to log in again!**
