### ISSUE TITLE
Login without password possible

### ISSUE THREAD

**Issue by Hoerli1337** [SoapboxRaceWorld/GameLauncher_NFSW#15]
- **Launcher Version:** 2.0.5.7
- **Operating system:** Windows 10 Pro (1909)
- **Antivirus/Firewall (if any):** Windows / Windows
- **Wine/Mono Version (if any):** Nope

I successfully registered once and started the game.
If I open the launcher again, the mail address is already in it. That's ok.
If I press Login without entering the password, the launcher successfully logs in with my account.
If I enter the password, I can also log in.

If I press Logout and log in again without entering a password, the login also works.

I don't think that's quite the intention, do you?
Or is "Remember my EMail Adress" also to be set equal to "Save my access data including password"?

**Comment by ghost** [comment]
That's because you have selected ![image](https://user-images.githubusercontent.com/6225233/68998988-edcf9e00-08b9-11ea-9430-0dd10d6fd3fb.png).
