### ISSUE TITLE
Launch Error on Linux 

### ISSUE THREAD

**Issue by Somamint** [SoapboxRaceWorld/GameLauncher_NFSW#150]
Launcher Version: 2.1.2.7
    Operating system: POP!OS 20.10
    Antivirus/Firewall (if any): None
    Wine/Mono Version (if any): lutris-nfsworld-5.4-x86_64 but tried also newer versions 

When i try to start the game i got this error.

https://ibb.co/QDLpGVG

**Comment by szymon420420** [comment]
Same at Ubuntu 20.04 :/

**Comment by Somamint** [comment]
I got it work! You need to use Launcher 2.1.6.6

**Comment by szymon420420** [comment]
Thanks bro !
