### ISSUE TITLE
Launcher sending unencrypted login data

### ISSUE THREAD

**Issue by March3wQa** [SoapboxRaceWorld/GameLauncher_NFSW#150]
- **Launcher Version:** V2.0.1.4BUILD-715C440
- **Operating system:** Microsoft Windows 10 Pro
- **Antivirus/Firewall (if any):** Bitdefender Antivirus/Bitdefender Firewall
- **Wine/Mono Version (if any):** None

I just want to say, that the login data sent by the launcher to the server is unencrypted, thus susceptible to man-in-the-middle attack (Bitdefender is blocking such transfers).

**Comment by metonator** [comment]
even original nfsw launcher did that. no need for fixes... also, is not launcher failure, its server software.

**Comment by metonator** [comment]
Also, to "somehow" fix mitm, we send password hash instead of real password.
