### ISSUE TITLE
I got the game to start, but a crtitical error accurs sbrw_crashdump Please help

### ISSUE THREAD

**Issue by Ksinfergo1** [SoapboxRaceWorld/GameLauncher_NFSW#154]
- **Launcher Version:** latest
- **Operating system:** wind 10
- **Antivirus/Firewall (if any): no
- **Wine/Mono Version (if any):** 
The critical sbrw crashdump error is followed by "Proccess nfsw.exe was killed by the task manager"

**Comment by musashiss** [comment]
I have the same Error at this moment, what can I do?
I´m with windows 11
