### ISSUE TITLE
Game Launcher Game Downloader (Missing LZMA File) 2.0.2.0 [Again]

### ISSUE THREAD

**Issue by 1DavidCarbon** [SoapboxRaceWorld/GameLauncher_NFSW#155]
- **Launcher Version:** 2.0.2.0
- **Operating system:** Windows
```
You forgot to include LZMA DDL file. Existing users might not see 
this issue but a complete fresh install will cause this error.
```
Funny or not (Most likely a meme) but the last time I reported this was on 2.0.0.20 haha.

**Comment by metonator** [comment]
I always forget to include it...

**Comment by metonator** [comment]
Kill me next time if it will re-happen once again...
