### ISSUE TITLE
The Undelying connection was closed

### ISSUE THREAD

**Issue by Kontar04** [SoapboxRaceWorld/GameLauncher_NFSW#155]
- **Launcher Version:** v2.1.7.6
- **Operating system:** Windows 10
- **Antivirus/Firewall (if any):** Avast Free
- **Wine/Mono Version (if any):** 

I downloaded the game normaly ; I can login normaly but when I press PLAY NOW this comes up:
![image](https://user-images.githubusercontent.com/67391135/112748644-c4eb0d00-8fc5-11eb-9cef-bc4995700930.png)

**Comment by pedro100phf** [comment]
I have this problem, is there any way to solve it?
