### ISSUE TITLE
i cant start the launcher

### ISSUE THREAD

**Issue by dudimgonnabreakmymonitor** [SoapboxRaceWorld/GameLauncher_NFSW#156]
- **Launcher Version:** 
- **Operating system:** 
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 

when i start up the launcher it says that the launcher is not allowed to be in a C:/ or D:/ ( rooted ) file how do i fix

**Comment by dudimgonnabreakmymonitor** [comment]
![εικόνα_2021-04-02_233312](https://user-images.githubusercontent.com/81798014/113451964-caa08280-940b-11eb-9af7-2273a1c06bc0.png)

**Comment by Allerek** [comment]
Read this once more, do not install launcher in there directories.
Launcher should be instaled in (for example).
[DiskLetter]:\NFSWLauncher

**Comment by TergelDaPro1337** [comment]
![Problem sovled](https://user-images.githubusercontent.com/83189976/116012427-1b825000-a633-11eb-8815-ce322c174862.JPG)
if you don't have the shown folder then make it
