### ISSUE TITLE
PROBLEM WITH MODLOADER

### ISSUE THREAD

**Issue by jonsjons2** [SoapboxRaceWorld/GameLauncher_NFSW#157]
EVERY TIME I CLICK TO LOG IN AND PLAY AFTER A FEW SECONDS OF THE MODNET ERROR, I HAVE TRIED EVERYTHING, I AM ALMOST GIVING UP. I HOPE TO HAVE A QUICK SOLUTION.
![WhatsApp Image 2021-04-06 at 21 32 59](https://user-images.githubusercontent.com/82067335/113793902-caf89080-971f-11eb-848c-0f5dd41bbf3d.jpeg)

**Comment by manhnt9** [comment]
Use launcher 2.1.6.6 instead.
