### ISSUE TITLE
Critical Error "Out of Memory"

### ISSUE THREAD

**Issue by Shawn608** [SoapboxRaceWorld/GameLauncher_NFSW#158]
After starting any event I crash and get a Out of memory error. i dont know why, i have 16gb of ram and the game is on a ssd. im on world online PL

- **Launcher Version:** 
- **Operating system:** 
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):**

**Comment by metonator** [comment]
Its because:

1. Incomplete download
2. Server went offline
3. You lost connection to server
