### ISSUE TITLE
Modnet files error

### ISSUE THREAD

**Issue by mastas00** [SoapboxRaceWorld/GameLauncher_NFSW#159]
- **Launcher Version:**  latest
- **Operating system:** windows 10 
- **Antivirus/Firewall (if any):** avast on silent mode 
- **Wine/Mono Version (if any):** 
i already tried redownloading and files scan

![81fd2e8741f7a58517f8ac1517afe119](https://user-images.githubusercontent.com/82365215/114353754-11158000-9b76-11eb-8ce4-50d58f8c3276.png)

**Comment by manhnt9** [comment]
I have this error too (Linux).
![image](https://user-images.githubusercontent.com/11463928/122640511-28e72280-d12a-11eb-9a17-ba1195615bb2.png)

**Comment by manhnt9** [comment]
Updating the launcher to 2.1.6.6 works.
