### ISSUE TITLE
Game Launcher 2.0.5.7 is not responding

### ISSUE THREAD

**Issue by lev275** [SoapboxRaceWorld/GameLauncher_NFSW#16]
Hello, my launcher is not responding after several tries.

I've already restarted my laptop but it's still unresponsive.
The chronology:
I opened my launcher, and suddenly it's unresponsive. 

Please fix this or give me a solution, thanks!

**Comment by lev275** [comment]
Also I've already reinstalled the launcher but it's still unresponsive. Another issue is the launcher status is always checking the moment it closed itself.

WINDOWS 10
Kaspersky Free

**Comment by ghost** [comment]
remove all files from launcher dir, excluding all dll files and its executable, then start again.

**Comment by lev275** [comment]
Hello, but it's still not working. It worked for a second, and after I
clicked Play Now, it became unresponsive again

**Comment by lev275** [comment]
Also it closed itself again
