### ISSUE TITLE
Gamelauncher does not work on the second disk

### ISSUE THREAD

**Issue by Dron500** [SoapboxRaceWorld/GameLauncher_NFSW#163]
- **Launcher Version:** newest
- **Operating system:** Win10
- **Antivirus/Firewall (if any):** no
- **Wine/Mono Version (if any):** 

the video shows that the game does not start

**Comment by Dron500** [comment]
![Screenshot_2021-04-18-00-24-09-212_com miui gallery](https://user-images.githubusercontent.com/82733259/115128256-c1eba700-9fdc-11eb-946a-a70596cc520b.jpg)
![Screenshot_2021-04-18-00-24-38-731_com miui videoplayer](https://user-images.githubusercontent.com/82733259/115128262-c912b500-9fdc-11eb-9236-e28ea6f25ee0.jpg)
![Screenshot_2021-04-18-00-25-56-315_com miui videoplayer](https://user-images.githubusercontent.com/82733259/115128264-cca63c00-9fdc-11eb-997e-8b1e59bb8740.jpg)


I can't send wideo

Game not start :(

**Comment by DavidCarbon** [comment]
Please provide the Launcher Log (Located in the Launcher Folder)
This can give the Launcher Division an insight how where it hanged.
