### ISSUE TITLE
Unable to Start Launcher..

### ISSUE THREAD

**Issue by zielony12** [SoapboxRaceWorld/GameLauncher_NFSW#168]
- **Launcher Version: latest** 
- **Operating system: ArchLinux with Linux 5.11.11** 
- **Antivirus/Firewall (if any): i dont have** 
- **Wine/Mono Version (if any): latest** 
i just created a new directory, selected it in installer, and i got this error:
![image](https://user-images.githubusercontent.com/68541652/117064881-0ab69600-ad27-11eb-80e5-fbe6fdce9309.png)

i got it every launch, and launcher crashes, my Settings.ini:

[GameLauncher]
InstallationDirectory = C:\nfsw
CDN = http://g2-sbrw.davidcarbon.download
Language = EN
DisableProxy = 0
DisableRPC = 0
IgnoreUpdateVersion = 
FilePermission = Not Set
GameIntegrity = Unknown
ProxyPort = 
FirewallLauncher = Error
FirewallGame = Error
WindowsDefender = Unknown

**Comment by Kethen** [comment]
got the same thing
version: 2.1.7.8
wine: https://github.com/Frogging-Family/wine-tkg-git/releases/tag/6.8.r0.g0f00e37c
installed dotnet462 and vcrun2019 using winetricks
![image](https://user-images.githubusercontent.com/22017945/117778574-5d84d600-b270-11eb-9404-087c9536025a.png)
