### ISSUE TITLE
Error, exitcode -2147483645

### ISSUE THREAD

**Issue by lev275** [SoapboxRaceWorld/GameLauncher_NFSW#17]
- Operating system: Windows 10
- Antivirus/Firewall (if any): Kaspersky Free

When I enter the game, during the first loading screen, the game suddenly crashed and show this message
![1575727977818806143958](https://user-images.githubusercontent.com/58520833/70375935-60baba80-1936-11ea-83be-471ee8fb4e11.jpg)

**Comment by ghost** [comment]
Corrupted files, redownload the game.
