### ISSUE TITLE
Cant register

### ISSUE THREAD

**Issue by firmanyudhis** [SoapboxRaceWorld/GameLauncher_NFSW#175]
- **Launcher Version:*2.1.7.8* 
- **Operating system:*win 10* 
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 
can give me solution about this case?
![image](https://user-images.githubusercontent.com/51564297/121691314-139e4280-caf1-11eb-975b-62689c4f1225.png)
and this
![image](https://user-images.githubusercontent.com/51564297/121691433-2fa1e400-caf1-11eb-8352-61747b0877d9.png)

**Comment by Turbski** [comment]
You selected the wrong server. IIRC, WorldUnited Development is not available to the public. Select any other server.
