### ISSUE TITLE
You are using the wrong (or unsigned) launcher

### ISSUE THREAD

**Issue by pappnase63** [SoapboxRaceWorld/GameLauncher_NFSW#176]
- **Launcher Version: 2.1.7.8 
- **Operating system: Windows 10
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 

Good evening, 

for a few days now when I log into the game launcher I have been getting the message: 

You are using the wrong (or unsigned) launcher, please update to the latest one. 

 
![grafik](https://user-images.githubusercontent.com/85902852/121949307-97a63380-cd58-11eb-97e5-0afc62b672a2.png)

Although I installed the current launcher (version 2.1.7.8), I reinstalled it again. But the mistake remains the same. 

The error only exists on the nightriderz server, on all other servers I can start the game without errors via the game launcher. 

What can I do to be able to play on the nightriderz server again? 

I ask for support. 

Thank you and best regards

**Comment by x-Ghosts** [comment]
Hello @pappnase63 , and sorry too for the late reply. 

Try to recently open your SBRW Launcher, it will ask you to download automatically the new Update version of the Actual Launcher that you're trying to use. Other than that, you can redirect yourself to the official Website of that server, named by **nightriderz.world** (Don't use the ** that I wrote there, it is used just to make the difference on the text) , and look for the page where it asks to download the launchers, you will have the access to the last update version of the Launchers.

Thanks for reading, and apologizes for the late reply.

**Comment by Zacam** [comment]
Only 2.1.8.4 (or newer, for PTB/Release Candidate versions) are allowed on NR.
