### ISSUE TITLE
ModNet error

### ISSUE THREAD

**Issue by Dron500** [SoapboxRaceWorld/GameLauncher_NFSW#178]
.
![Bez tytułu](https://user-images.githubusercontent.com/82733259/123885728-5152f600-d94e-11eb-9533-3182eb8f5528.jpg)

**Comment by x-Ghosts** [comment]
Hello @Dron500 ! 

Try to disable the proxy on the ⚙️ settings of your launcher. And also, give a try too with restarting the Wifi Router, it fixes most of the time, the issue.

Inform me asap, if the issue has been fixed or not !

**Comment by Dron500** [comment]
12:10:28.47 [ CORE] DISCORD: Initializing Rich Presense Core
12:10:28.61 [ INFO] CURRENT DATE: 07/05/2021
12:10:28.61 [BUILD] BUILD: GameLauncher 2.1.8.4_07-02-21-A
12:10:28.61 [ INFO] LAUNCHER: Detecting OS
12:10:28.61 [SYSTM] SYSTEM: Detected OS: Windows 10 64 Bit
12:10:28.61 [SYSTM] SYSTEM: Windows Build: 19041
12:10:28.61 [SYSTM] SYSTEM: NT Version: Microsoft Windows NT 10.0.19042.0
12:10:28.75 [SYSTM] SYSTEM: Video Card: Intel(R) HD Graphics 5500
12:10:28.80 [SYSTM] SYSTEM: Driver Version: 20.19.15.4642
12:10:28.80 [ INFO] CORE: Setting up current directory: D:\NFS
12:10:28.80 [ INFO] CORE: Checking current directory
12:10:28.82 [ INFO] SETTINGS FILE: Random Generated Default Port -> 2019
12:10:28.99 [ INFO] WINDOWS FIREWALL: Already Exlcuded SBRW - Game Launcher
12:10:29.13 [ INFO] WINDOWS FIREWALL: Already Exlcuded SBRW - Game Launcher Updater
12:10:29.13 [ INFO] PROXY: Starting Proxy (From Startup)
12:10:29.13 [ INFO] PROXY: Local Proxy Server has Fully Initialized (Splash Screen [Program.cs])
12:10:34.53 [ INFO] CORE: https://api.worldunited.gg/serverlist.json is Online!
12:10:34.55 [  URL] LIST CORE: Loading Server List from: https://api.worldunited.gg/serverlist.json
12:10:34.75 [  URL] LIST CORE: Loaded Server List from: https://api.worldunited.gg/serverlist.json
12:10:34.94 [ INFO] CERTIFICATE STORE: Setting Common Name -> Carbon Crew CA
12:10:34.94 [ INFO] CERTIFICATE STORE: Setting Subject Name -> CN=Carbon Crew CA, OU=Certificate Authority, O=Carbon Crew Productions, C=US
12:10:34.94 [ INFO] CERTIFICATE STORE: Setting Serial Number -> 4B93595BA5D71D15
12:10:34.94 [ INFO] CERTIFICATE STORE: Setting Root CA File Name -> CC-CA
12:10:34.94 [ INFO] CERTIFICATE STORE: Setting Root CA File URL -> http://crl.carboncrew.org/CC-CA.cer
12:10:34.96 [ INFO] CERTIFICATE STORE: Found Root CA [CN=Carbon Crew CA, OU=Certificate Authority, O=Carbon Crew Productions, C=US]
12:10:34.96 [ INFO] CERTIFICATE STORE: Serial Number [4B93595BA5D71D15]
12:10:35.47 [ INFO] SIGNED: True
12:10:35.66 [ INFO] LAUNCHER UPDATER: Setting Latest Version -> 1.0.0.6
12:10:35.66 [ INFO] LAUNCHER UPDATER: Latest Version -> 1.0.0.6
12:10:35.66 [BUILD] LAUNCHER UPDATER BUILD: GameLauncherUpdater 1.0.0.6
12:10:35.66 [ INFO] LAUNCHER UPDATER: Latest GameLauncherUpdater!
12:10:35.77 [ INFO] LAUNCHER UPDATE: Latest Version -> 2.1.8.4
12:10:35.78 [ CORE] LAUNCHER: Checking InstallationDirectory: D:\nfsfiles
12:10:35.78 [ CORE] WINDOWS DEFENDER: Found 'WindowsDefender' key! Its value is Not Supported
12:10:35.78 [VISUL] CORE: Starting MainScreen
12:10:35.91 [DEBUG] PROXY: Checking if Proxy Is Disabled from User Settings! It's value is 0
12:10:35.97 [VISUL] CORE: Entering mainScreen_Load
12:10:35.99 [ CORE] CORE: Setting Parent Window location
12:10:35.99 [ CORE] LAUNCHER: NFSW Download Source is now: https://cdn.worldunited.gg
12:10:35.99 [VISUL] CORE: Applyinng ContextMenu
12:10:36.00 [ CORE] LAUNCHER: Checking for password
12:10:36.00 [ CORE] LAUNCHER: Restoring last saved email and password
12:10:36.00 [ CORE] LAUNCHER: Setting server list
12:10:36.02 [ CORE] SERVERLIST: Checking...
12:10:36.02 [ CORE] SERVERLIST: Setting first server in list
12:10:36.02 [ CORE] SERVERLIST: Checking if server is set on INI File
12:10:36.02 [ CORE] SERVERLIST: Re-Checking if server is set on INI File
12:10:36.02 [ CORE] SERVERLIST: Found something!
12:10:36.02 [ CORE] SERVERLIST: Checking if server exists on our database
12:10:36.02 [ CORE] SERVERLIST: Server found! Checking ID
12:10:36.02 [ CORE] SERVERLIST: ID is 1
12:10:36.02 [ CORE] SERVERLIST: ID set correctly
12:10:36.05 [ CORE] SERVERLIST: Triggering server change
12:10:36.07 [ CORE] SERVERLIST: All done
12:10:36.07 [ CORE] LAUNCHER: Re-checking InstallationDirectory: D:\nfsfiles
12:10:36.10 [ CORE] CORE: 'GetServerInformation' from all Servers in Server List and Download Selected Server Banners
12:10:36.27 [ INFO] WINDOWS FIREWALL: Already Exlcuded SBRW - Game
12:10:36.27 [ CORE] PERMISSIONS: Checking File! It's value is Set
12:10:36.27 [  URL] WEBCLIENTWITHTIMEOUT: Calling URL -> http://game.worldunited.gg:8080/Engine.svc/GetServerInformation
12:10:36.47 [ INFO] SERVER PING: 128ms for WorldUnited OFFICIAL
12:10:36.49 [ INFO] SERVER PING: 128ms for WorldUnited OFFICIAL
12:10:36.57 [  URL] WEBCLIENTWITHTIMEOUT: Calling URL -> http://horizon.nightriderz.world:8080/Engine.svc/GetServerInformation
12:10:36.63 [  URL] WEBCLIENTWITHTIMEOUT: Calling URL -> http://92.63.111.195:8680/soapbox-race-core/Engine.svc/GetServerInformation
12:10:36.69 [  URL] WEBCLIENTWITHTIMEOUT: Calling URL -> https://core.sparkserver.io/soapbox-race-core/Engine.svc/GetServerInformation
12:10:36.83 [  URL] WEBCLIENTWITHTIMEOUT: Calling URL -> http://155.138.131.23:8080/core/Engine.svc/GetServerInformation
12:10:37.17 [  URL] WEBCLIENTWITHTIMEOUT: Calling URL -> http://worldonline.pl:2137/Engine.svc/GetServerInformation
12:10:37.24 [  URL] WEBCLIENTWITHTIMEOUT: Calling URL -> http://209.97.187.156:8080/Engine.svc/GetServerInformation
12:10:41.57 [ CORE] LAUNCHER: Installing ModNet
12:10:42.05 [DEBUG] MODNET CORE: 7z.dll Is Up to Date!
12:10:42.10 [DEBUG] MODNET CORE: LIBEAY32.dll Is Up to Date!
12:10:42.13 [DEBUG] MODNET CORE: ModLoader.asi Is Up to Date!
12:10:42.14 [DEBUG] MODNET CORE: SSLEAY32.dll Is Up to Date!
12:10:42.14 [ WARN] MODNET CORE: dinput8.dll Does not match SHA Hash on File Server -> Online Hash: '4cd7adfa4898d80cc6e4f4645066d8157e9bad1bf18950f6f4798abdce20bf56'
12:10:42.36 [ERROR] MODNET CORE: An exception occurred during a WebClient request.
12:10:46.17 [ INFO] PROXY: Local Proxy Server has Shutdown (Main Screen)

**Comment by Dron500** [comment]
Try to disable the proxy on the ⚙️ settings of your launcher-How?

**Comment by Zacam** [comment]
The :gear: Icon in the upper right of the Launcher is a button that opens the "Settings" Screen where you can check a box to disable the Proxy.

However, Proxy does not matter with regards to ModNet files downloads, it only comes into play when loading to the game server connection in question (when it launches nfsw.exe)

To that end, I'd suggest looking to Discord for a Release Candidate Build or await Release of 2.1.8.6 and see if that improves things, since with 2.1.8.5 you can change the "WebClient" calls if needed.

Also be aware that some AntiVirus/Web Protection software (such as Malware Bytes or SmartScreen) can cause that error by "False Positive" flagging that the ModLoader.asi comes from that location; so make sure the Launcher is allowed to access "cdn.soapboxrace.world"
