### ISSUE TITLE
The launcher asks for VC++ 2015-2019 runtimes, while I have already installed 2015-2022.

### ISSUE THREAD

**Issue by nlgxzef** [SoapboxRaceWorld/GameLauncher_NFSW#183]
Steps to reproduce:
- Run the launcher.
- It will ask for the VC++ 2015-2019 runtimes. First for x86 version, and then for x64.
![SBRW Launcher VC x86](https://user-images.githubusercontent.com/1937572/127199379-fd24c91d-b1d6-41f1-b46a-0ac642709de3.png)

I already have the 2015-2022 version of them installed, which came from Visual Studio 2022.
![image](https://user-images.githubusercontent.com/1937572/127199665-9f02b0fc-7bc6-4cb4-95bb-afabf045debc.png)

- If I press OK, it waits for a while and the launcher starts successfully.
- If I press Cancel, I get an error like this and the logo stays on the screen until I kill the launcher process:
![image](https://user-images.githubusercontent.com/1937572/127200097-3b63457b-0acf-4cef-8565-3fc54b73737f.png)

Here are my specs:
- **Launcher Version:** 2.1.8.4
- **Operating system:** Windows 11 Pro, Build 22000.100
- **Antivirus/Firewall (if any):** Windows Defender
- **Wine/Mono Version (if any):** Nope, I'm on Windows.

The issue isn't vital as I can get the launcher and the game working after I press OK for both dialogs. (VC Setup probably exits with an error code 0, telling that a newer version is already installed.)

Hope it gets fixed with the next update. Thanks in advance!

**Comment by DavidCarbon** [comment]
Heyo! 

This issue should probably be checked at before the next Launcher Release, since it (2.1.8.6) will lock users out if they don't pass this requirement check.

**Comment by Zacam** [comment]
Correct, the "Minimum" version check for VC Redist was set to ``InstalledVersion.StartsWith("v14.2")`` and the Win 11 2022 is 14.30; so we'll need to change that to a Minimum to ``>=`` against.

**Comment by DavidCarbon** [comment]
Issue as been fixed in the Development Branch
