### ISSUE TITLE
LAUNCHER ERROR

### ISSUE THREAD

**Issue by Estashiba** [SoapboxRaceWorld/GameLauncher_NFSW#187]
- **Launcher Version:** 
- **Operating system:** 
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 

I NEED HELP... WHAT IS THE SOLUTION?
![image](https://user-images.githubusercontent.com/41027691/129818357-43f70410-b0ad-45f8-b55f-be1f0a10b5c9.png)

**Comment by Zacam** [comment]
That is seeming to indicate that your UserSettings.xml file is incorrect or corrupted/damaged.
If you delete it, the launcher will make a new one, failing that, the game will once it launches.

**Comment by Estashiba** [comment]
> Eso parece indicar que su archivo UserSettings.xml es incorrecto o está dañado.
> Si lo eliminas, el lanzador creará uno nuevo, de lo contrario, el juego lo hará una vez que se lance.

but where is this file? because it does not appear in the launcher directory.

**Comment by Zacam** [comment]
It won't, it's a NFSW game file that gets stored in your AppData "Roaming" folder, under 'Need for Speed World' then 'Settings'

**Comment by Estashiba** [comment]
It helped me, it was solved but now after installing the game, not when you hit play. The screen goes black and then the game closes.
