### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by Trasher97** [SoapboxRaceWorld/GameLauncher_NFSW#188]
- **Launcher Version: 2.1.8.4
- **Operating system: Windows 10
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 
![Captura de pantalla 2021-08-22 161726](https://user-images.githubusercontent.com/89358838/130369257-9e6babf9-a9a7-4ea0-815f-4ace205033af.jpg)
![Captura de pantalla 2021-08-22 162449](https://user-images.githubusercontent.com/89358838/130369263-8078ddfa-d4fe-473b-9876-57323dd97dfd.jpg)
when I am in a race or in some menu the game closes and tells me out of memory
Before I played the old nfs world on my pc, I don't know if now the requirements are more demanding or something, sorry for my English

**Comment by Zacam** [comment]
API Errors have zero to do with server communications errors; the API is just where a server/cdn "List" is obtained from.
As show in the screenshot, it still was able to resolve a Working API.

"Out of Memory" isn't a system requirements issue relating to RAM on the PC; but a poor state error handle in the nfsw.exe that reports communications errors as being "Out of Memory" or "!Out of Memory!"
