### ISSUE TITLE
After opening the launcher it says 'unable to connect to server list API' and then if i proceed it says 'unable to connect to any cdn list api.please check your connection'
Windows firewall defender is off and i'm running the latest version of the launcher.Any solutions?

### ISSUE THREAD

**Issue by sebyss15** [SoapboxRaceWorld/GameLauncher_NFSW#194]
00:45:51.55 [       CORE] DISCORD: Initializing Rich Presence Core
00:45:51.67 [      SYSTM] NET-FRAMEWORK: Supported Installed Version
00:45:51.71 [       INFO] SPLASH SCREEN: Attempting to Start Thread
00:45:51.72 [       INFO] SPLASH SCREEN: Thread has now Started
00:45:51.72 [       INFO] CURRENT DATE: 11/03/2021
00:45:51.72 [   CHECKING] LAUNCHER MIGRATION: Appdata and/or Roaming Folders
00:45:51.72 [   COMPLETE] LAUNCHER MIGRATION
00:45:51.72 [   CHECKING] LAUNCHER XML: If File Exists or Not
00:45:51.72 [   COMPLETE] LAUNCHER XML
00:45:51.72 [      BUILD] BUILD: GameLauncher 2.1.9.00_10-10-21-B
00:45:51.72 [   CHECKING] OS: Detecting
00:45:51.72 [      SYSTM] SYSTEM: Detected OS: Windows 10 64 Bit
00:45:51.72 [      SYSTM] SYSTEM: Windows Build: 19041
00:45:51.72 [      SYSTM] SYSTEM: NT Version: Microsoft Windows NT 10.0.19043.0
00:45:51.93 [      SYSTM] SYSTEM: Video Card: AMD Radeon (TM) R7 M340
00:45:51.98 [      SYSTM] SYSTEM: Driver Version: 27.20.12033.1007
00:45:51.98 [   COMPLETE] OS: Detected
00:45:51.98 [   CHECKING] SETUP: Setting Launcher Folder Directory
00:45:51.98 [   COMPLETE] SETUP: Current Directory now Set at -> C:\New folder (2)\
00:45:51.98 [   CHECKING] FOLDER LOCATION: Checking Launcher Folder Directory
00:45:51.98 [   COMPLETE] FOLDER LOCATION: Done
00:45:51.98 [   CHECKING] WRITE TEST: Launcher Folder Test
00:45:51.98 [   COMPLETE] WRITE TEST: Passed
00:45:51.98 [   CHECKING] INI FILES: Doing Nullsafe
00:45:51.99 [       INFO] SETTINGS FILE: Random Generated Default Port -> 2018
00:45:51.99 [       INFO] SETTINGS FILE: Choosen WebCall Method -> WebClient
00:45:51.99 [   COMPLETE] INI FILES: Done
00:45:51.99 [   FUNCTION] APPLICATION: Setting Language
00:45:51.99 [   COMPLETE] APPLICATION: Done Setting Language 'en'
00:45:51.99 [   CHECKING] JSON: Servers File
00:45:51.99 [   CHECKING] JSON: Done
00:45:51.99 [   CHECKING] PROXY: Checking if Proxy Is Disabled from User Settings! It's value is 0
00:45:51.99 [       CORE] PROXY: Starting Proxy (From Startup)
00:45:51.99 [       INFO] PROXY: Local Proxy Server has Fully Initialized (Splash Screen [Program.cs])
00:45:52.37 [   COMPLETE] PROXY: Started
00:45:52.37 [       INFO] REDISTRIBUTABLE: Moved to Function
00:45:52.37 [   CHECKING] REDISTRIBUTABLE: Is Installed or Not
00:45:52.37 [       INFO] REDISTRIBUTABLE: 32-bit 2015-2019 VC++ Redistributable Package is Installed
00:45:52.37 [       INFO] REDISTRIBUTABLE: 64-bit 2015-2019 VC++ Redistributable Package is Installed
00:45:52.37 [   COMPLETE] REDISTRIBUTABLE: Done
00:45:52.37 [       INFO] ID: Moved to Function
00:45:57.44 [       INFO] LIST: Moved to Function
00:45:57.44 [   CHECKING] LIST CORE: Creating Language List
00:45:57.52 [   CHECKING] LIST CORE: Done
00:45:57.52 [       INFO] API: Moved to Function
00:45:57.52 [   CHECKING] API: Checking Status
00:45:57.52 [   CHECKING] API Status: WorldUnited
00:45:57.52 [   CHECKING] CHECKING STATUS: https://api.worldunited.gg/serverlist.json
00:46:12.56 [   COMPLETE] CHECKING STATUS: https://api.worldunited.gg/serverlist.json [WebException]
00:46:12.56 [      ERROR] CORE: https://api.worldunited.gg/serverlist.json Additional Details -> The operation has timed out
00:46:12.56 [      ERROR] CORE: https://api.worldunited.gg/serverlist.json has Encounterd an Error -> Timeout
00:46:12.56 [   COMPLETE] API Status: WorldUnited
00:46:12.56 [   CHECKING] API Status: DavidCarbon
00:46:12.56 [   CHECKING] CHECKING STATUS: https://api-sbrw.davidcarbon.download/serverlist.json
00:46:27.57 [   COMPLETE] CHECKING STATUS: https://api-sbrw.davidcarbon.download/serverlist.json [WebException]
00:46:27.57 [      ERROR] CORE: https://api-sbrw.davidcarbon.download/serverlist.json Additional Details -> The operation has timed out
00:46:27.57 [      ERROR] CORE: https://api-sbrw.davidcarbon.download/serverlist.json has Encounterd an Error -> Timeout
00:46:27.57 [   COMPLETE] API Status: DavidCarbon
00:46:27.57 [   CHECKING] API Status: DavidCarbon [Second]
00:46:27.57 [   CHECKING] CHECKING STATUS: http://api2-sbrw.davidcarbon.download/serverlist.json
00:46:42.60 [   COMPLETE] CHECKING STATUS: http://api2-sbrw.davidcarbon.download/serverlist.json [WebException]
00:46:42.60 [      ERROR] CORE: http://api2-sbrw.davidcarbon.download/serverlist.json Additional Details -> The operation has timed out
00:46:42.60 [      ERROR] CORE: http://api2-sbrw.davidcarbon.download/serverlist.json has Encounterd an Error -> Timeout
00:46:42.60 [   COMPLETE] API Status: DavidCarbon [Second]
00:46:42.60 [   CHECKING] API: Test #2
00:46:48.82 [       WARN] PRE-CHECK: User has Bypassed 'No Internet Connection' Check and will Continue
00:46:51.91 [   COMPLETE] API: Test #2 Done
00:46:51.91 [       INFO] LIST CORE: Moved to Function
00:46:51.91 [   CHECKING] SERVER LIST CORE: Creating Server List
00:46:51.92 [      ERROR] SERVER LIST CORE: Value cannot be null.
Parameter name: value
00:46:51.92 [ ERROR CODE] SERVER LIST CORE: -2147467261
00:46:51.92 [ FULL ERROR] SERVER LIST CORE: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at GameLauncher.App.Classes.LauncherCore.Lists.ServerListUpdater.GetList()
00:46:51.92 [   COMPLETE] SERVER LIST CORE: Server List has no Elements
00:46:51.92 [       INFO] CERTIFICATE STORE: Moved to Function
00:46:51.93 [   CHECKING] CERTIFICATE STORE: Is Installed or Not
00:47:34.43 [       INFO] CERTIFICATE STORE: Setting Common Name -> Carbon Crew CA
00:47:34.43 [       INFO] CERTIFICATE STORE: Setting Subject Name -> CN=Carbon Crew CA, OU=Certificate Authority, O=Carbon Crew Productions, C=US
00:47:34.43 [       INFO] CERTIFICATE STORE: Setting Serial Number -> 4B93595BA5D71D15
00:47:34.43 [       INFO] CERTIFICATE STORE: Setting Root CA File Name -> CC-CA
00:47:34.43 [       INFO] CERTIFICATE STORE: Setting Root CA File URL -> http://crl.carboncrew.org/CC-CA.cer
00:47:34.45 [       INFO] CERTIFICATE STORE: Found Root CA [CN=Carbon Crew CA, OU=Certificate Authority, O=Carbon Crew Productions, C=US]
00:47:34.45 [       INFO] CERTIFICATE STORE: Serial Number [4B93595BA5D71D15]
00:47:34.50 [   COMPLETE] CERTIFICATE STORE: Done
00:47:34.50 [   CHECKING] CERTIFICATE CHECK: Is Signed or Not
00:47:44.64 [   COMPLETE] CERTIFICATE CHECK: Done
00:47:44.64 [       INFO] VERIFIED: Moved to Function
00:47:44.69 [       INFO] SIGNED: True
00:47:44.69 [       INFO] LAUNCHER UPDATER: Moved to Function
00:47:44.69 [   CHECKING] LAUNCHER UPDATER: Is Version Up to Date or not
00:47:44.95 [       INFO] LAUNCHER UPDATER: Setting Latest Version -> 1.0.1.02
00:47:44.95 [       INFO] LAUNCHER UPDATER: Latest Version -> 1.0.1.02
00:47:44.95 [      BUILD] LAUNCHER UPDATER BUILD: GameLauncherUpdater 1.0.1.02
00:47:44.95 [       INFO] LAUNCHER UPDATER: Latest GameLauncherUpdater!
00:47:44.95 [   COMPLETE] LAUNCHER UPDATER: Done
00:47:44.95 [       INFO] LAUNCHER UPDATE: Moved to Function
00:47:44.96 [   CHECKING] LAUNCHER UPDATE: Is Version Up to Date or not
00:47:45.13 [       INFO] LAUNCHER UPDATE: GitHub Latest Version -> 2.1.9.00
00:47:45.13 [   COMPLETE] LAUNCHER UPDATE: Done
00:47:45.14 [   COMPLETE] LAUNCHER POPUP: Update to Date
00:47:45.14 [       INFO] FIRST TIME RUN: Moved to Function
00:47:45.14 [       INFO] SPLASH SCREEN: Attempting to Stop Thread
00:47:45.14 [   COMPLETE] SPLASH SCREEN: Thread is now Stopped
00:47:45.14 [   CHECKING] LAUNCHER: Checking Game Installation
00:47:45.14 [       CORE] LAUNCHER: First run!
00:47:45.18 [   CHECKING] API: Test #3
00:47:51.49 [   CHECKING] API: Test #3 Done
00:47:51.50 [      ERROR] CDN LIST CORE: Value cannot be null.
Parameter name: value
00:47:51.50 [ ERROR CODE] CDN LIST CORE: -2147467261
00:47:51.50 [ FULL ERROR] CDN LIST CORE: System.ArgumentNullException: Value cannot be null.
Parameter name: value
   at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
   at Newtonsoft.Json.JsonConvert.DeserializeObject[T](String value, JsonSerializerSettings settings)
   at GameLauncher.App.Classes.LauncherCore.Lists.CDNListUpdater.GetList()
00:48:00.00 [      ERROR] THREAD EXCEPTION: Object reference not set to an instance of an object.
00:48:00.00 [ ERROR CODE] THREAD EXCEPTION: -2147467261
00:48:00.00 [ FULL ERROR] THREAD EXCEPTION: System.NullReferenceException: Object reference not set to an instance of an object.
   at GameLauncher.App.UI_Forms.Welcome_Screen.WelcomeScreen.Save_Click(Object sender, EventArgs e)
   at System.Windows.Forms.Control.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnClick(EventArgs e)
   at System.Windows.Forms.Button.OnMouseUp(MouseEventArgs mevent)
   at System.Windows.Forms.Control.WmMouseUp(Message& m, MouseButtons button, Int32 clicks)
   at System.Windows.Forms.Control.WndProc(Message& m)
   at System.Windows.Forms.ButtonBase.WndProc(Message& m)
   at System.Windows.Forms.Button.WndProc(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.OnMessage(Message& m)
   at System.Windows.Forms.Control.ControlNativeWindow.WndProc(Message& m)
   at System.Windows.Forms.NativeWindow.Callback(IntPtr hWnd, Int32 msg, IntPtr wparam, IntPtr lparam)

**Comment by kari0ca** [comment]
Same here, with firewall and anti virus disabled, i cant connect to the API Server
