### ISSUE TITLE
Out of memory

### ISSUE THREAD

**Issue by MarokBoy** [SoapboxRaceWorld/GameLauncher_NFSW#198]
Release_2.1.9.0002
Windows
Antivirus and Firewall Off

I keep getting a waring about: out of memory.... but i have 16GB and only 7 gig RAM was being used. It cant be my storage because it is only half full.

![Schermafbeelding 2021-12-26 192612](https://user-images.githubusercontent.com/96697944/147416994-0785208e-dff0-4308-b0eb-726ecdfb0c59.png)

**Comment by AhmedAbdelnabySalout** [comment]
any fix?
