### ISSUE TITLE
Hardcoded CDN for No Connection is Misleading

### ISSUE THREAD

**Issue by Zacam** [SoapboxRaceWorld/GameLauncher_NFSW#20]
MainScreen.cs
Line 410: Defunct location, no longer works (Old WOPL CDN Address).

Catch on line 610 tries to list/instantiate a CDN instead of displaying a connection error message (even if the CDN Location is valid and working, it's also out of date to the cdn_list itself)

**Comment by DavidCarbon** [comment]
https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/blob/7d96b507d55052120df5480c423810ea2b19d130/GameLauncher/App/MainScreen.cs#L470

https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/blob/7d96b507d55052120df5480c423810ea2b19d130/GameLauncher/App/MainScreen.cs#L609-L615

**Comment by ghost** [comment]
Good catch! Gonna fix this asap.

**Comment by ghost** [comment]
Should be fixed. Tests needed.
