### ISSUE TITLE
Is possible a port to ARM Linux?

### ISSUE THREAD

**Issue by Chiqui1234ok** [SoapboxRaceWorld/GameLauncher_NFSW#200]
Hi! The launcher could be rewritten in NET Core and then compiled for ARM Linux but, how about the game itself? Could be difficult as hell like already dead OpenNFS repo? 😅

I'm web developer with basic/old skills on C & C++, so If we have a good chance to make this happen, I can start with something between my free time.

Tomorrow I'll download the game just for digging about game files

**Comment by Zacam** [comment]
If Lutris/WINE/Mono are able to run and encapsulate nfsw on ARM the same as they do on non-ARM, then nothing needs to be recompiled; and trying to do so would be an inefficient expenditure of time.

Official Builds for the launcher will only ever be released as compiled for Windows, as the native application being run (nfsw.exe) is only compiled for such runtime environment.
