### ISSUE TITLE
Error launching the game:.links should not exist upon startup

### ISSUE THREAD

**Issue by Superfast2** [SoapboxRaceWorld/GameLauncher_NFSW#204]
![error 1](https://user-images.githubusercontent.com/107345466/173225369-3557c310-09fe-4629-8305-201c2f30e9ea.jpg)
![Error 2](https://user-images.githubusercontent.com/107345466/173225370-80713e4a-3ce9-4003-9024-12fbd832fbf7.jpg)
Hi guys I have installed the game just like I saw on Youtube (downloaded all,extracted to a blank folder in "C" and ran as administrator,although it shows me this every time and I can't run the game.
any helpers out there?

**Comment by Zacam** [comment]
IF this is still occurring, "Verify Game Files" in the Settings Screen (gear button, top right)
