### ISSUE TITLE
Could connect with my ps4 controller

### ISSUE THREAD

**Issue by skydeed** [SoapboxRaceWorld/GameLauncher_NFSW#208]
- **Launcher Version:** 2.1.0.0002
- **Operating system:** Window11
- **Antivirus/Firewall (if any):** mcAfee
- **Wine/Mono Version (if any):** 

when i connect my ps4 controller, every button doenst work but it works fine for other application, pls help

**Comment by Zacam** [comment]
Controller support can be dependent on Server Mod Files configurations, you're better off seeking assistance in a given servers Discord (which is linked in the Launcher under the Server Banner image).
