### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by mayyconCMD** [SoapboxRaceWorld/GameLauncher_NFSW#217]
- **Launcher Version:** Release_2.2.0.0
- **Operating system:** Win 10
- **Antivirus/Firewall (if any):** Windows Defender
- **Wine/Mono Version (if any):** 

Everytime i try to lauch the games this happens

[SBRCrashDump_CL0_2022.11.14_19.17.58.txt](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/10006407/SBRCrashDump_CL0_2022.11.14_19.17.58.txt)
![image](https://user-images.githubusercontent.com/118216429/201748436-93175709-cfcb-4c12-996f-8050e28bc401.png)

**Comment by gabimalmeida** [comment]
managed to solve?

**Comment by AviationSG** [comment]
Having the same issue currently...

**Comment by TheKASTeTx** [comment]
I have the same problem, help me please <3

**Comment by Zildrik** [comment]
![22](https://user-images.githubusercontent.com/120746278/208165801-60f6ef74-b55d-4580-a854-19079f812edd.png)
help me

**Comment by TheKASTeTx** [comment]
Hi i dont know how :(Temat: Re: [SoapboxRaceWorld/GameLauncher_NFSW] Critical Error (Issue #217)Data: 2022-12-16 19:35Nadawca: "Zildrik" ***@***.***&gt;Adresat: "SoapboxRaceWorld/GameLauncher_NFSW" ***@***.***&gt;; DW: "KASTeT" ***@***.***&gt;; "Comment" ***@***.***&gt;; 


help me

**Comment by Zacam** [comment]
"Verify Game Files" in the Settings Screen (Gear button, top right) and try again.
