### ISSUE TITLE
Ciritcal error

### ISSUE THREAD

**Issue by Steb28** [SoapboxRaceWorld/GameLauncher_NFSW#218]
I have this error everytime i try to launch the game
[SBRCrashDump_CL0_2022.11.11_20.39.36.txt](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/10025536/SBRCrashDump_CL0_2022.11.11_20.39.36.txt)

**Comment by TheDuke203** [comment]
In the launcher click on the settings cog on the top right and verify your game files, you will have a few files to download
What I think is happening is that the game is downloading some of the files but isn't updating to the latest build or something like that cause for me I had like 5800+ files left to download
