### ISSUE TITLE
Access Violation Error on Windows 11

### ISSUE THREAD

**Issue by Pinsi2007** [SoapboxRaceWorld/GameLauncher_NFSW#219]
- **Version 2.2.0.0** 
- **Windows 11** 
- **Kaspersky Total Security** 
- **No Wine or Mono** 
I just finished setting up everything on SBRW, however, upon starting the game I get an error that says: "Access Violation" with its corresponding error code. I've only seen issues regarding the same error on Linux, so if someone had the same problem and was able to fix it, a reply would be very appreciated.

**Comment by Zildrik** [comment]
![22](https://user-images.githubusercontent.com/120746278/208165690-f9fc895c-dd2c-441e-843b-0835832425c8.png)
help mi

**Comment by Zacam** [comment]
"Verify Game Files" in the Settings Screen (Gear button, top right) and try again.
