### ISSUE TITLE
Game Crash: Access Violation (0xC0000005)

### ISSUE THREAD

**Issue by Hakunek** [SoapboxRaceWorld/GameLauncher_NFSW#22]
- **Launcher Version:** 
2.0.9.6
- **Operating system:** 
Windows 10
- **Antivirus/Firewall (if any):** 
none
- **Wine/Mono Version (if any):** 
none

After clicking "Play Now" button game starts and after a few moments of displaying loading screen it crashes with alert "Game Crash: Access Violation (0xC0000005)".

**Comment by ghost** [comment]
please run file validation tool from settings

**Comment by Hakunek** [comment]
> please run file validation tool from settings

If you meant to uncheck option "disable process validate files" it does nothing(everything happens exactly the same), not with restart or without it.

**Comment by ghost** [comment]
Yup, got that, there was a bug with that. Please try running it again.

**Comment by Hakunek** [comment]
Still the same(updated, unchecked that thing and the same)

**Comment by Hakunek** [comment]
ok, reinstall after that update worked ^-^
Thanks for your time!
