### ISSUE TITLE
Access Violation (0xc0000005) | Windows 10

### ISSUE THREAD

**Issue by KG535YTgithub** [SoapboxRaceWorld/GameLauncher_NFSW#220]
When im selecting any CDN and it starts the game it shows error "Access Violation (0xc0000005)" on Windows 10. I got latest version and i've heard that there is a File Validator but i don't know how to download it beacuse on the site https://docs.sbrw.davidcarbon.download/launcher/settings/official/misc#disable-process-that-validate-files
there **ISN'T** any download button or download link. Please tell me how to fix it! 

PS the location of files is good! But i think there are some missing files but i don't know.

Question me anything that will help!

![obraz_2022-12-04_201835134](https://user-images.githubusercontent.com/106016741/205510786-00722669-2e89-4453-a644-9b3132e0a555.png)

**Comment by Zildrik** [comment]
![22](https://user-images.githubusercontent.com/120746278/208165585-adb2867c-a8a2-4b69-8983-0cc363efeadb.png)
help mi

**Comment by Zacam** [comment]
"Verify Game Files" in the Settings Screen (Gear button, top right) and try again.
