### ISSUE TITLE
b

### ISSUE THREAD

**Issue by Zildrik** [SoapboxRaceWorld/GameLauncher_NFSW#221]
## Summary

One paragraph explanation of the feature.

## Additional context

Add any other context or screensh
![22](https://user-images.githubusercontent.com/120746278/208166645-03c15ec3-11ae-462c-8c71-1aa23576dfa5.png)
ots about the feature request here.

**Comment by Zacam** [comment]
"Verify Game Files" in the Settings Screen (Gear button, top right) and try again.
