### ISSUE TITLE
help me

### ISSUE THREAD

**Issue by Zildrik** [SoapboxRaceWorld/GameLauncher_NFSW#222]
- **Launcher Version:** 
- **Operating system:** 
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 

![22](https://user-images.githubusercontent.com/120746278/208167121-8f829f4b-3ced-4394-9cff-afb24703737c.png)

**Comment by Zacam** [comment]
"Verify Game Files" in Settings Screen (Gear button, top right) and try again.
