### ISSUE TITLE
Critical error/access violation

### ISSUE THREAD

**Issue by mlodszykami** [SoapboxRaceWorld/GameLauncher_NFSW#224]
- **Launcher Version:** 2.2.0.2
- **Operating system:** Windows 10
- **Antivirus/Firewall (if any):** only windows defender 
When i clicked play game loaded and after a while screen froze and it poped up this:
![screen 1](https://user-images.githubusercontent.com/97168212/208975504-a7f9f91d-8a4a-49f4-8027-eb3f052c94b2.PNG)
Then after loading it one more time game started loading a little bit longer and now i get this error: 
![screen 2](https://user-images.githubusercontent.com/97168212/208975279-d38b40a2-d5dd-455e-bdc2-f41f953568a0.PNG)

Can someone please help?

**Comment by Zacam** [comment]
"Verify Game Files" (even if you update or change Launcher version) in the Settings Screen (Gear button, top right)
