### ISSUE TITLE
Launcher Error

### ISSUE THREAD

**Issue by Puzzler017** [SoapboxRaceWorld/GameLauncher_NFSW#227]
after updating
the error occurred after updating. I deleted all the game files and downloaded it again and I can't even open the launcher

- **SBRW.Launcher 2.2.0.2 - (11-05-22-D)** 
- **windows 10 22H2 :** 
- **windows defender(turned off)** 
- **Wine/Mono Version (if any):** 

![sbrw](https://user-images.githubusercontent.com/121909163/210460841-28e71c92-eb47-407c-a20c-9689bdfba1d6.png)
[Launcher.log](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/10340429/Launcher.log)

**Comment by Zacam** [comment]
The "Settings.ini" Configuration File in the Launcher folder is corrupted or incorrect.

Rename it to something else, and try again. (You will need to re-tell the Launcher where nfsw.exe is located at)
