### ISSUE TITLE
DiscordRPC Broken

### ISSUE THREAD

**Issue by Zacam** [SoapboxRaceWorld/GameLauncher_NFSW#23]
- **Launcher Version:** Any past 2.0.8.8
- **Operating system:** Windows 7 and Windows 10 (1909)
- **Antivirus/Firewall (if any):** N/A
- **Wine/Mono Version (if any):** N/A

Discord RPC inoperable, version 2.0.8.8 is the last working version that interacts with Discord.
The DiscordRPC.dll is identical across all versions since, so something code wise or endpoint wise has negatively impacted operations of it.

Still trying to code-walk/compile my own version to track down the culprit, will update if/when I find it.

**Comment by ghost** [comment]
Yea, thats known issue, and i am alzo searching to fix that. First mind was
to move all to new SDK.

W dniu czwartek, 13 lutego 2020 Zacam <notifications@github.com> napisał(a):

>
>    - *Launcher Version:* Any past 2.0.8.8
>    - *Operating system:* Windows 7 and Windows 10 (1909)
>    - *Antivirus/Firewall (if any):* N/A
>    - *Wine/Mono Version (if any):* N/A
>
> Discord RPC inoperable, version 2.0.8.8 is the last working version that
> interacts with Discord.
> The DiscordRPC.dll is identical across all versions since, so something
> code wise or endpoint wise has negatively impacted operations of it.
>
> Still trying to code-walk/compile my own version to track down the
> culprit, will update if/when I find it.

**Comment by Zacam** [comment]
Package/Include moving forward the following 2 files to all future "Release.zip" packages to fix:
GameLauncher.exe.config
GameLauncher.exe.manifest

**Comment by ghost** [comment]
This should be fixed since 4 releases, closing that.
