### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by CzionF1** [SoapboxRaceWorld/GameLauncher_NFSW#230]
- **Launcher Version:** 2.2.0.2
- **Operating system:** Windows 10 pro
- **Antivirus/Firewall (if any):** Windows Defender
- **Wine/Mono Version (if any):** 
- I cant open the game
![Captura de pantalla (261)](https://user-images.githubusercontent.com/122167530/211159080-87bb8242-0d63-4809-b739-eb130160a5c6.png)
[SBRCrashDump_CL0_2023.01.07_15.47.42.txt](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/10366637/SBRCrashDump_CL0_2023.01.07_15.47.42.txt)
[SBRCrashDump_CL0_2023.01.07_15.47.42.dmp.txt](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/10366642/SBRCrashDump_CL0_2023.01.07_15.47.42.dmp.txt)
github dont support .dmp but i change the format to .txt

**Comment by CzionF1** [comment]
Czion#3918 in discord

**Comment by ultraUser76** [comment]
Verifying files fix the issue for me. Good luck.
