### ISSUE TITLE
Critical error

### ISSUE THREAD

**Issue by 12360** [SoapboxRaceWorld/GameLauncher_NFSW#232]
- **Launcher Version:** 2.2.0.2
- **Operating system:** Windows 10 Home
- **Antivirus/Firewall (if any):** Windows defender
- **Wine/Mono Version (if any):** 
 
![image](https://user-images.githubusercontent.com/26607683/212466584-1c03fa37-64c0-4157-9177-375f857bdd25.png)
 
 
[SBRCrashDump_CL0_2023.01.14_09.58.31.txt](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/10417097/SBRCrashDump_CL0_2023.01.14_09.58.31.txt)
[SBRCrashDump_CL0_2023.01.14_09.58.31dmp.txt](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/10417098/SBRCrashDump_CL0_2023.01.14_09.58.31.txt)

I cant open the game. Any solutions?

**Comment by evelynnagonysembrace** [comment]
same issue :/

**Comment by 12360** [comment]
Solution is the verify GameFiles in settings in luncher.
