### ISSUE TITLE
Incorrect Event Type Icon

### ISSUE THREAD

**Issue by Zacam** [SoapboxRaceWorld/GameLauncher_NFSW#24]
- **Launcher Version:** Any
- **Operating system:** Any
- **Antivirus/Firewall (if any):** N/A
- **Wine/Mono Version (if any):** N/A

Events.json:

{"id": "83","trackname": "Hastings","type": "gamemode_sprint"},

should read:

{"id": "83","trackname": "Hastings","type": "gamemode_circuit"},

**Comment by Zacam** [comment]
#25 
Submitted Pull request to update Circuit/Sprint mismatches and add a few more events to the list

**Comment by ghost** [comment]
Alright, closing since it's fixed in new version.
