### ISSUE TITLE
ERROR - 255 (0xFF)

### ISSUE THREAD

**Issue by nightznero** [SoapboxRaceWorld/GameLauncher_NFSW#27]
- **Launcher Version:** v2.0.11
- **Operating system:**  Win7
- **Antivirus/Firewall (if any):** Off
- **Wine/Mono Version (if any):** 
![Screenshot_1](https://user-images.githubusercontent.com/61750641/75797161-0a161e80-5d75-11ea-8765-d8afe1804cab.jpg)
I can play NIGHTRIDERS but unlimitedgg i cannot..... fix that please

**Comment by ghost** [comment]
Not a launcher kssue, contact server administrator
