### ISSUE TITLE
Different car models of friends are visible and unable to play together

### ISSUE THREAD

**Issue by bansalnaman15** [SoapboxRaceWorld/GameLauncher_NFSW#29]
-Operating system: Windows 10 
-Antivirus/Firewall (if any): OFF 
Unable to join my friends for a private match, also different models of cars are visible to each other, we both have nissan240sx, also names are different. 
![WhatsApp Image 2020-03-22 at 9 00 16 PM](https://user-images.githubusercontent.com/43118067/77253576-2ecd2a00-6c81-11ea-9594-729f3abc632b.jpeg)
![WhatsApp Image 2020-03-22 at 9 00 21 PM](https://user-images.githubusercontent.com/43118067/77253579-3096ed80-6c81-11ea-8d76-dba4e3b489a5.jpeg)

**Comment by Zacam** [comment]
That's a server sync related issue, not a GameLauncher related issue.
