### ISSUE TITLE
The game don't work in linux since the 2.1.0.3

### ISSUE THREAD

**Issue by leillo1975** [SoapboxRaceWorld/GameLauncher_NFSW#31]
- **Launcher Version:** 2.1.0.3
- **Operating system:** Ubuntu 18.04
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** Lutris-nfsworld-5.4

Before updating I can't connect to server, now, with the last version I have this problem when I try to execute the launcher:
![Captura de pantalla de 2020-03-28 22-06-03](https://user-images.githubusercontent.com/551821/77833805-6126cd80-7140-11ea-98fb-aa385ecb5639.png)
![Captura de pantalla de 2020-03-28 22-06-50](https://user-images.githubusercontent.com/551821/77833818-76036100-7140-11ea-8261-563ad1b43370.png)

**Comment by ghost** [comment]
It's an issue on line 13 of "Self.cs" file, sent a "workaround" to new
maintainer.

sob., 28 mar 2020 o 22:07 leillo1975 <notifications@github.com> napisał(a):

**Comment by Clem0908** [comment]
Same thing here, even after the patch.
wine version : 5.5

**Comment by tadeumx1** [comment]
Same here, but i am having this problem in Windows 10

I want to run this game, please anyone fix this error

**Comment by tadeumx1** [comment]
@metonator Can you help ?

**Comment by ghost** [comment]
No longer maintaining it, however, linux fix has been pull requested already.

**Comment by GabrielLourenco** [comment]
Hello people. I was experiencing at least the above problem and I managed to correct it by doing the following:
When reading laucher.log, I noticed the following lines:
```
[DEBUG] Loading serverlist from: https://api.worldunited.gg/serverlist.json
[DEBUG] Restoring last saved email and password
[DEBUG] Setting server list
[ERROR] O tempo limite da operação foi atingido
[DEBUG] SERVERLIST: Checking...
[DEBUG] SERVERLIST: Setting first server in list
[DEBUG] SERVERLIST: InvalidArgument=Value '1' não é um valor válido para 'SelectedIndex'.
Nome do parâmetro: SelectedIndex
```
So, I accessed the link https://api.worldunited.gg/serverlist.json to get the list of servers, copied and pasted it in the file `servers.json` and ran laucher again and now it worked.

**Comment by Chiqui1234ok** [comment]
> Hello people. I was experiencing at least the above problem and I managed to correct it by doing the following:
> When reading laucher.log, I noticed the following lines:
> 
> ```
> [DEBUG] Loading serverlist from: https://api.worldunited.gg/serverlist.json
> [DEBUG] Restoring last saved email and password
> [DEBUG] Setting server list
> [ERROR] O tempo limite da operação foi atingido
> [DEBUG] SERVERLIST: Checking...
> [DEBUG] SERVERLIST: Setting first server in list
> [DEBUG] SERVERLIST: InvalidArgument=Value '1' não é um valor válido para 'SelectedIndex'.
> Nome do parâmetro: SelectedIndex
> ```
> 
> So, I accessed the link https://api.worldunited.gg/serverlist.json to get the list of servers, copied and pasted it in the file `servers.json` and ran laucher again and now it worked.

Unfortunally, that didn't solve the error in my case (tested with Lutris and different Wine versions like lutris-nfsworld-5.4, proton 4 & proton 5 and playonlinux 5.3).
My machine is Ryzen 7 2700X + RX 590 and runs Xubuntu 19.10

**Comment by Chiqui1234ok** [comment]
My error is
``` bash
Application does not support just-in-time (JIT)\ndebugging. See the end of this message for details.\n\n************** Exception Text **************\nSystem.Net.WebException: The request was canceled
  at System.Net.WebOperation.CheckThrowDisposed (System.Boolean throwIt, System.Runtime.ExceptionServices.ExceptionDispatchInfo& field) [0x00029] in <f508ff7dc2d3475abfc25b6b60600edf>:0 
  at System.Net.WebOperation.ThrowIfClosedOrDisposed (System.Threading.CancellationToken cancellationToken) [0x00011] in <f508ff7dc2d3475abfc25b6b60600edf>:0 
  at System.Net.WebOperation.ThrowIfClosedOrDisposed () [0x00006] in <f508ff7dc2d3475abfc25b6b60600edf>:0 
  at System.Net.WebConnectionStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00019] in <f508ff7dc2d3475abfc25b6b60600edf>:0 
  at System.IO.StreamReader.ReadBuffer () [0x00028] in <a1336bab325642fd867e87ca7626bada>:0 
  at System.IO.StreamReader.ReadToEnd () [0x00059] in <a1336bab325642fd867e87ca7626bada>:0 
  at GameLauncher.App.Classes.Auth.ClassicAuth.Login (System.String email, System.String password) [0x0008d] in <7b7375e327fa4444a5ff359c4ee49bf4>:0 
  at GameLauncher.MainScreen.loginButton_Click (System.Object sender, System.EventArgs e) [0x000f8] in <7b7375e327fa4444a5ff359c4ee49bf4>:0 
  at System.Windows.Forms.Control.OnClick (System.EventArgs e) [0x0001f] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Button.OnClick (System.EventArgs e) [0x00037] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Button.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x0009a] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Control.WmMouseUp (System.Windows.Forms.Message& m, System.Windows.Forms.MouseButtons button, System.Int32 clicks) [0x001c3] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x005a0] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.ButtonBase.WndProc (System.Windows.Forms.Message& m) [0x0011f] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Button.WndProc (System.Windows.Forms.Message& m) [0x00056] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.OnMessage (System.Windows.Forms.Message& m) [0x00001] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x000b3] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.NativeWindow.Callback (System.IntPtr hWnd, System.Int32 msg, System.IntPtr wparam, System.IntPtr lparam) [0x00030] in <afc71676634a41889c6929c14e8a57bd>:0 
```

**Comment by leillo1975** [comment]
Now , with the last version works again

**Comment by obsidian29** [comment]
I seem to be having the same issue.

- **Launcher Version:** 2.1.0.8
- **Operating system:** Ubuntu Linux 16.04 LTS
- **Antivirus/Firewall (if any):**
- **Wine/Mono Version (if any):** Wine 5.0

I was originally getting the error that OP got, but now getting the following after allowing it to fully download and then attempting again to register:

`Application does not support just-in-time (JIT)\ndebugging. See the end of this message for details.\n\n************** Exception Text **************\nSystem.PlatformNotSupportedException: Only supported on Windows Vista or newer.
  at MS.WindowsAPICodePack.Internal.CoreHelpers.ThrowIfNotVista () [0x00010] in <423d1f22ee84411bbd0d40f49dbb72fd>:0 
  at Microsoft.WindowsAPICodePack.Dialogs.TaskDialog..ctor () [0x0003c] in <423d1f22ee84411bbd0d40f49dbb72fd>:0 
  at MeTonaTOR.MessageBox.Show (System.Windows.Forms.IWin32Window owner, System.String text, System.String caption, System.String instruction, MeTonaTOR.MessageBox+_MessageBoxButtons buttons, MeTonaTOR.MessageBox+_MessageBoxIcon icon) [0x00001] in <5e39a2fdd0e5428cafc2b7c9b7f11417>:0 
  at GameLauncher.MainScreen.registerButton_Click (System.Object sender, System.EventArgs e) [0x0033d] in <5e39a2fdd0e5428cafc2b7c9b7f11417>:0 
  at System.Windows.Forms.Control.OnClick (System.EventArgs e) [0x0001f] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Button.OnClick (System.EventArgs e) [0x00037] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Button.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x0009a] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Control.WmMouseUp (System.Windows.Forms.Message& m, System.Windows.Forms.MouseButtons button, System.Int32 clicks) [0x001c3] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x005a0] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.ButtonBase.WndProc (System.Windows.Forms.Message& m) [0x0011f] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Button.WndProc (System.Windows.Forms.Message& m) [0x00056] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.OnMessage (System.Windows.Forms.Message& m) [0x00001] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x000b3] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.NativeWindow.Callback (System.IntPtr hWnd, System.Int32 msg, System.IntPtr wparam, System.IntPtr lparam) [0x00030] in <afc71676634a41889c6929c14e8a57bd>:0 

\n************** Loaded Assemblies **************\nmscorlib\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/4.5/mscorlib.dll\n----------------------------------------\nGameLauncher\n    Assembly Version: 2.1.0.8\n    Win32 Version: 2.1.0.8\n    CodeBase: file:///Z:/home/newuser/nfsworld/GameLauncher.exe\n----------------------------------------\nSystem\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll\n----------------------------------------\nSystem.Windows.Forms\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Windows.Forms/4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll\n----------------------------------------\nINIFileParser\n    Assembly Version: 2.5.2.0\n    Win32 Version: 2.5.2\n    CodeBase: file:///Z:/home/newuser/nfsworld/INIFileParser.dll\n----------------------------------------\nNewtonsoft.Json\n    Assembly Version: 12.0.0.0\n    Win32 Version: 12.0.3.23909\n    CodeBase: file:///Z:/home/newuser/nfsworld/Newtonsoft.Json.dll\n----------------------------------------\nSystem.Core\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll\n----------------------------------------\nNancy.Hosting.Self\n    Assembly Version: 2.0.0.0\n    Win32 Version: 2.0.0.0\n    CodeBase: file:///Z:/home/newuser/nfsworld/Nancy.Hosting.Self.dll\n----------------------------------------\nSystem.Drawing\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Drawing/4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll\n----------------------------------------\nAccessibility\n    Assembly Version: 4.0.0.0\n    Win32 Version: \n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/Accessibility/4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll\n----------------------------------------\nDiscordRPC\n    Assembly Version: 1.0.150.0\n    Win32 Version: 1.0.150.0\n    CodeBase: file:///Z:/home/newuser/nfsworld/DiscordRPC.dll\n----------------------------------------\nSystem.Configuration\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Configuration/4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll\n----------------------------------------\nSystem.Xml\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll\n----------------------------------------\nMono.Security\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.0.0.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll\n----------------------------------------\nI18N\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.0.0.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/I18N/4.0.0.0__0738eb9f132ed756/I18N.dll\n----------------------------------------\nI18N.West\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.0.0.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/I18N.West/4.0.0.0__0738eb9f132ed756/I18N.West.dll\n----------------------------------------\nNancy\n    Assembly Version: 2.0.0.0\n    Win32 Version: 2.0.0.0\n    CodeBase: file:///Z:/home/newuser/nfsworld/Nancy.dll\n----------------------------------------\nSystem.Management\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Management/4.0.0.0__b03f5f7f11d50a3a/System.Management.dll\n----------------------------------------\nFlurl\n    Assembly Version: 2.8.2.0\n    Win32 Version: 2.8.2.0\n    CodeBase: file:///Z:/home/newuser/nfsworld/Flurl.dll\n----------------------------------------\nSystem.Net.Http\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Net.Http/4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll\n----------------------------------------\nFlurl.Http\n    Assembly Version: 2.4.2.0\n    Win32 Version: 2.4.2.0\n    CodeBase: file:///Z:/home/newuser/nfsworld/Flurl.Http.dll\n----------------------------------------\nMicrosoft.WindowsAPICodePack\n    Assembly Version: 1.1.0.0\n    Win32 Version: 1.1.0.0\n    CodeBase: file:///Z:/home/newuser/nfsworld/Microsoft.WindowsAPICodePack.dll\n----------------------------------------\nAnonymously Hosted DynamicMethods Assembly\n    Assembly Version: 0.0.0.0\n    Win32 Version: n/a\n    CodeBase: \n----------------------------------------\nMicrosoft.CSharp\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/Microsoft.CSharp/4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll\n----------------------------------------\nMicrosoft.WindowsAPICodePack.Shell\n    Assembly Version: 1.1.0.0\n    Win32 Version: 1.1.0.0\n    CodeBase: file:///Z:/home/newuser/nfsworld/Microsoft.WindowsAPICodePack.Shell.dll\n----------------------------------------\nPresentationFramework\n    Assembly Version: 3.0.0.0\n    Win32 Version: 3.0.6920.5738 built by: QFE\n    CodeBase: file:///Z:/home/newuser/nfsworld/PresentationFramework.dll\n----------------------------------------\nPresentationCore\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C\n    CodeBase: file:///Z:/home/newuser/nfsworld/PresentationCore.dll\n----------------------------------------\nWindowsBase\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/WindowsBase/4.0.0.0__31bf3856ad364e35/WindowsBase.dll\n----------------------------------------\nSystem.Numerics\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Numerics/4.0.0.0__b77a5c561934e089/System.Numerics.dll\n----------------------------------------\nSystem.Runtime.Serialization\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Runtime.Serialization/4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll\n----------------------------------------\nSystem.Data\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Data/4.0.0.0__b77a5c561934e089/System.Data.dll\n----------------------------------------\n\n************** JIT Debugging **************\nApplication does not support Windows Forms just-in-time (JIT)\ndebugging. Contact the application author for more\ninformation.\n`

If there's anything I can do to help you fix this for everyone, please let me know. We wouldn't have NFS World without you guys and I'd love to do anything I can to help.

**Comment by Chiqui1234ok** [comment]
> I seem to be having the same issue.
> 
> * **Launcher Version:** 2.1.0.8
> * **Operating system:** Ubuntu Linux 16.04 LTS
> * **Antivirus/Firewall (if any):**
> * **Wine/Mono Version (if any):** Wine 5.0
> 
> I was originally getting the error that OP got, but now getting the following after allowing it to fully download and then attempting again to register:
> 
> `Application does not support just-in-time (JIT)\ndebugging. See the end of this message for details.\n\n************** Exception Text **************\nSystem.PlatformNotSupportedException: Only supported on Windows Vista or newer.
> at MS.WindowsAPICodePack.Internal.CoreHelpers.ThrowIfNotVista () [0x00010] in <423d1f22ee84411bbd0d40f49dbb72fd>:0
> at Microsoft.WindowsAPICodePack.Dialogs.TaskDialog..ctor () [0x0003c] in <423d1f22ee84411bbd0d40f49dbb72fd>:0
> at MeTonaTOR.MessageBox.Show (System.Windows.Forms.IWin32Window owner, System.String text, System.String caption, System.String instruction, MeTonaTOR.MessageBox+_MessageBoxButtons buttons, MeTonaTOR.MessageBox+_MessageBoxIcon icon) [0x00001] in <5e39a2fdd0e5428cafc2b7c9b7f11417>:0
> at GameLauncher.MainScreen.registerButton_Click (System.Object sender, System.EventArgs e) [0x0033d] in <5e39a2fdd0e5428cafc2b7c9b7f11417>:0
> at System.Windows.Forms.Control.OnClick (System.EventArgs e) [0x0001f] in :0
> at System.Windows.Forms.Button.OnClick (System.EventArgs e) [0x00037] in :0
> at System.Windows.Forms.Button.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x0009a] in :0
> at System.Windows.Forms.Control.WmMouseUp (System.Windows.Forms.Message& m, System.Windows.Forms.MouseButtons button, System.Int32 clicks) [0x001c3] in :0
> at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x005a0] in :0
> at System.Windows.Forms.ButtonBase.WndProc (System.Windows.Forms.Message& m) [0x0011f] in :0
> at System.Windows.Forms.Button.WndProc (System.Windows.Forms.Message& m) [0x00056] in :0
> at System.Windows.Forms.Control+ControlNativeWindow.OnMessage (System.Windows.Forms.Message& m) [0x00001] in :0
> at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x000b3] in :0
> at System.Windows.Forms.NativeWindow.Callback (System.IntPtr hWnd, System.Int32 msg, System.IntPtr wparam, System.IntPtr lparam) [0x00030] in :0
> 
> \n************** Loaded Assemblies **************\nmscorlib\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/4.5/mscorlib.dll\n----------------------------------------\nGameLauncher\n Assembly Version: 2.1.0.8\n Win32 Version: 2.1.0.8\n CodeBase: file:///Z:/home/newuser/nfsworld/GameLauncher.exe\n----------------------------------------\nSystem\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll\n----------------------------------------\nSystem.Windows.Forms\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Windows.Forms/4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll\n----------------------------------------\nINIFileParser\n Assembly Version: 2.5.2.0\n Win32 Version: 2.5.2\n CodeBase: file:///Z:/home/newuser/nfsworld/INIFileParser.dll\n----------------------------------------\nNewtonsoft.Json\n Assembly Version: 12.0.0.0\n Win32 Version: 12.0.3.23909\n CodeBase: file:///Z:/home/newuser/nfsworld/Newtonsoft.Json.dll\n----------------------------------------\nSystem.Core\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll\n----------------------------------------\nNancy.Hosting.Self\n Assembly Version: 2.0.0.0\n Win32 Version: 2.0.0.0\n CodeBase: file:///Z:/home/newuser/nfsworld/Nancy.Hosting.Self.dll\n----------------------------------------\nSystem.Drawing\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Drawing/4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll\n----------------------------------------\nAccessibility\n Assembly Version: 4.0.0.0\n Win32 Version: \n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/Accessibility/4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll\n----------------------------------------\nDiscordRPC\n Assembly Version: 1.0.150.0\n Win32 Version: 1.0.150.0\n CodeBase: file:///Z:/home/newuser/nfsworld/DiscordRPC.dll\n----------------------------------------\nSystem.Configuration\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Configuration/4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll\n----------------------------------------\nSystem.Xml\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll\n----------------------------------------\nMono.Security\n Assembly Version: 4.0.0.0\n Win32 Version: 4.0.0.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll\n----------------------------------------\nI18N\n Assembly Version: 4.0.0.0\n Win32 Version: 4.0.0.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/I18N/4.0.0.0__0738eb9f132ed756/I18N.dll\n----------------------------------------\nI18N.West\n Assembly Version: 4.0.0.0\n Win32 Version: 4.0.0.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/I18N.West/4.0.0.0__0738eb9f132ed756/I18N.West.dll\n----------------------------------------\nNancy\n Assembly Version: 2.0.0.0\n Win32 Version: 2.0.0.0\n CodeBase: file:///Z:/home/newuser/nfsworld/Nancy.dll\n----------------------------------------\nSystem.Management\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Management/4.0.0.0__b03f5f7f11d50a3a/System.Management.dll\n----------------------------------------\nFlurl\n Assembly Version: 2.8.2.0\n Win32 Version: 2.8.2.0\n CodeBase: file:///Z:/home/newuser/nfsworld/Flurl.dll\n----------------------------------------\nSystem.Net.Http\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Net.Http/4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll\n----------------------------------------\nFlurl.Http\n Assembly Version: 2.4.2.0\n Win32 Version: 2.4.2.0\n CodeBase: file:///Z:/home/newuser/nfsworld/Flurl.Http.dll\n----------------------------------------\nMicrosoft.WindowsAPICodePack\n Assembly Version: 1.1.0.0\n Win32 Version: 1.1.0.0\n CodeBase: file:///Z:/home/newuser/nfsworld/Microsoft.WindowsAPICodePack.dll\n----------------------------------------\nAnonymously Hosted DynamicMethods Assembly\n Assembly Version: 0.0.0.0\n Win32 Version: n/a\n CodeBase: \n----------------------------------------\nMicrosoft.CSharp\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/Microsoft.CSharp/4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll\n----------------------------------------\nMicrosoft.WindowsAPICodePack.Shell\n Assembly Version: 1.1.0.0\n Win32 Version: 1.1.0.0\n CodeBase: file:///Z:/home/newuser/nfsworld/Microsoft.WindowsAPICodePack.Shell.dll\n----------------------------------------\nPresentationFramework\n Assembly Version: 3.0.0.0\n Win32 Version: 3.0.6920.5738 built by: QFE\n CodeBase: file:///Z:/home/newuser/nfsworld/PresentationFramework.dll\n----------------------------------------\nPresentationCore\n Assembly Version: 4.0.0.0\n Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C\n CodeBase: file:///Z:/home/newuser/nfsworld/PresentationCore.dll\n----------------------------------------\nWindowsBase\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/WindowsBase/4.0.0.0__31bf3856ad364e35/WindowsBase.dll\n----------------------------------------\nSystem.Numerics\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Numerics/4.0.0.0__b77a5c561934e089/System.Numerics.dll\n----------------------------------------\nSystem.Runtime.Serialization\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Runtime.Serialization/4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll\n----------------------------------------\nSystem.Data\n Assembly Version: 4.0.0.0\n Win32 Version: 4.6.57.0\n CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Data/4.0.0.0__b77a5c561934e089/System.Data.dll\n----------------------------------------\n\n************** JIT Debugging **************\nApplication does not support Windows Forms just-in-time (JIT)\ndebugging. Contact the application author for more\ninformation.\n`
> 
> If there's anything I can do to help you fix this for everyone, please let me know. We wouldn't have NFS World without you guys and I'd love to do anything I can to help.

Hi! I'm not the dev but the error seems related to Windows version and not having Windows Forms installed.
Try changing the Windows version in your Wine prefix (to Windows 7) and install Windows Forms 32 bits.
Then, restart Windows (That option is on winetricks if I've remember well) and try again.

I didn't test this launcher because I have a lot of work! In one or two days, I'm free hehe

**Comment by Zacam** [comment]
Literally says in the beginning "Only supported on Windows Vista or newer."

Specifically, the .NET and Visual C++ Runtimes attached/supported require .NET Framework 4.6 or newer and MSVCR2015 (or 2017 or the "replaces both of those" 2015-2019) which need 7 SP 1 or 8.1; and the Forms shim DLL's provided require Vista minimum.

**Comment by ghost** [comment]
The issue should be already solved in newer update. Tested under Ubuntu 20.04 with Lutris
