### ISSUE TITLE
Comctl32.dll

### ISSUE THREAD

**Issue by Loloczek** [SoapboxRaceWorld/GameLauncher_NFSW#36]
- **Launcher Version:**  2.1.0.4
- **Operating system:**  Windows 7
- **Antivirus/Firewall (if any):** All Off
- **Wine/Mono Version (if any):** none

Problem is 
![image](https://user-images.githubusercontent.com/63798238/79467412-0aedd180-7ffe-11ea-8e54-18d555b0382f.png)

**Comment by ghost** [comment]
W wersji 2.1.2.0 ten błąd zniknie już definitywnie.
