### ISSUE TITLE
A fatal crash

### ISSUE THREAD

**Issue by AKASuper19** [SoapboxRaceWorld/GameLauncher_NFSW#37]
- **Launcher Version:** 2.1.0.4
- **Operating system:** Windows 10
- **Antivirus/Firewall (if any):** All off
- **Wine/Mono Version (if any):** none
I cant get out because the game crashes
![Error NFSW](https://user-images.githubusercontent.com/63826394/79520537-54e1b200-8014-11ea-9d89-f6eebabddf5f.png)
![Error NFSW 2](https://user-images.githubusercontent.com/63826394/79520475-2b288b00-8014-11ea-9a8f-e583e2204a5f.png)

**Comment by BOREKDJ** [comment]
help, I have the problem with version 2.1.0.8 too

how to fix it ??

**Comment by ghost** [comment]
This looks like a corrupted game install, please redownload game
