### ISSUE TITLE
Cant connect to the Apex Server

### ISSUE THREAD

**Issue by iTzDead1998** [SoapboxRaceWorld/GameLauncher_NFSW#39]
If I want to connect server on the apex I get the always following announcement.
Can somebody help me there? 
![nfsw](https://user-images.githubusercontent.com/36365743/36072932-6a8d63c4-0f28-11e8-884a-4885268142cd.PNG)
 Sorry for my english. I am from Germany

**Comment by FliessendWasser** [comment]
Try updating your launcher - the most recent version is [1.9.1.9](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/releases/tag/1.9.1.9).

After updating, choose "APEX Open Beta US", as the EU server does not seem to work, and the seems to be bugged as of now.
