### ISSUE TITLE
Chat crash the game on Linux

### ISSUE THREAD

**Issue by Clem0908** [SoapboxRaceWorld/GameLauncher_NFSW#39]
- **Launcher Version:** 2.1.0.6
- **Operating system:** Ubuntu 19.10
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** wine 5.6
The game works perfectly until I choose a language to chat. Within about 10 seconds, the game get stucked.

**Comment by ghost** [comment]
Wine bug, use lutris to install and play nfsw

**Comment by Clem0908** [comment]
Thanks ! It works ! My Xbox One gamepad is not recognized but fun is still here ;)
