### ISSUE TITLE
Game can't start on Linux

### ISSUE THREAD

**Issue by YunoGasai17** [SoapboxRaceWorld/GameLauncher_NFSW#40]
- **Launcher Version:** 2.1.0.6
- **Operating system:** Arch Linux
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** lutris-nfsworld-5.4
![Soapbox](https://user-images.githubusercontent.com/44075079/80262682-8c90cf80-868e-11ea-9f41-a597f5e6305a.png)
"Game Crash with exitcode: 3 (0x3)"
I tried logging in to multiple servers but I get the same result.

**Comment by Clem0908** [comment]
Hi ! I've got the same error with 2.1.0.4 launcher. I just disabled dxvk and it works !

**Comment by Chiqui1234ok** [comment]
Fedora 32, Lutris install, Launcher 2.1.0.4 "Linux Fix" says this when trying to log-in:

`Application does not support just-in-time (JIT)\ndebugging. See the end of this message for details.\n\n************** Exception Text **************\nSystem.Net.WebException: The request was canceled
  at System.Net.WebOperation.CheckThrowDisposed (System.Boolean throwIt, System.Runtime.ExceptionServices.ExceptionDispatchInfo& field) [0x00029] in <f508ff7dc2d3475abfc25b6b60600edf>:0
  at System.Net.WebOperation.ThrowIfClosedOrDisposed (System.Threading.CancellationToken cancellationToken) [0x00011] in <f508ff7dc2d3475abfc25b6b60600edf>:0
  at System.Net.WebOperation.ThrowIfClosedOrDisposed () [0x00006] in <f508ff7dc2d3475abfc25b6b60600edf>:0
  at System.Net.WebConnectionStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00019] in <f508ff7dc2d3475abfc25b6b60600edf>:0
  at System.IO.StreamReader.ReadBuffer () [0x00028] in <a1336bab325642fd867e87ca7626bada>:0
  at System.IO.StreamReader.ReadToEnd () [0x00059] in <a1336bab325642fd867e87ca7626bada>:0
  at GameLauncher.App.Classes.Auth.ClassicAuth.Login (System.String email, System.String password) [0x0008d] in <7b7375e327fa4444a5ff359c4ee49bf4>:0
  at GameLauncher.MainScreen.loginButton_Click (System.Object sender, System.EventArgs e) [0x000f8] in <7b7375e327fa4444a5ff359c4ee49bf4>:0
  at System.Windows.Forms.Control.OnClick (System.EventArgs e) [0x0001f] in <afc71676634a41889c6929c14e8a57bd>:0
  at System.Windows.Forms.Button.OnClick (System.EventArgs e) [0x00037] in <afc71676634a41889c6929c14e8a57bd>:0
  at System.Windows.Forms.Button.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x0009a] in <afc71676634a41889c6929c14e8a57bd>:0
  at System.Windows.Forms.Control.WmMouseUp (System.Windows.Forms.Message& m, System.Windows.Forms.MouseButtons button, System.Int32 clicks) [0x001c3] in <afc71676634a41889c6929c14e8a57bd>:0
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x005a0] in <afc71676634a41889c6929c14e8a57bd>:0
  at System.Windows.Forms.ButtonBase.WndProc (System.Windows.Forms.Message& m) [0x0011f] in <afc71676634a41889c6929c14e8a57bd>:0
  at System.Windows.Forms.Button.WndProc (System.Windows.Forms.Message& m) [0x00056] in <afc71676634a41889c6929c14e8a57bd>:0
  at System.Windows.Forms.Control+ControlNativeWindow.OnMessage (System.Windows.Forms.Message& m) [0x00001] in <afc71676634a41889c6929c14e8a57bd>:0
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x000b3] in <afc71676634a41889c6929c14e8a57bd>:0
  at System.Windows.Forms.NativeWindow.Callback (System.IntPtr hWnd, System.Int32 msg, System.IntPtr wparam, System.IntPtr lparam) [0x00030] in <afc71676634a41889c6929c14e8a57bd>:0`

**Comment by Chiqui1234ok** [comment]
Lutris log says a lot of things! My problem it could be due server connection issues? (I have good internet connection)

`Running /home/santiagogimenez/.local/share/lutris/runners/wine/lutris-5.6-2-x86_64/bin/wine /games/Lutris/SoapBox/GameLauncher.exe
Initial process has started with pid 17468
Game is considered started.
gamemodeauto: 
wine: configuration in L"/games/Lutris/SoapBox/prefix" has been updated.
Application path: Z:\games\Lutris\SoapBox
Game path: Z:\games\Lutris\SoapBox\GameFiles
[DEBUG] Setting up current directory: Z:\games\Lutris\SoapBox
[DEBUG] Checking current directory
[DEBUG] Checking Proxy
[DEBUG] Starting MainScreen
[DEBUG] Entered mainScreen
INFO: Attempting a new connection
INFO: RPC Connection Started
TRACE: ============================
TRACE: Assembly:             DiscordRPC, Version=1.0.150.0, Culture=neutral, PublicKeyToken=null
TRACE: Pipe:                 DiscordRPC.IO.ManagedNamedPipeClient
TRACE: Platform:             Microsoft Windows NT 10.0.17134.0
TRACE: applicationID:        540651192179752970
TRACE: targetPipe:           0
TRACE: POLL_RATE:            1000
TRACE: _maxRtQueueSize:      512
TRACE: _maxRxQueueSize:      0
TRACE: ============================
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(0)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to discord-ipc-0
[DEBUG] Setting SSL Protocol
[DEBUG] Detecting OS
[DEBUG] Detected OS: Fedora 32 (Workstation Edition)
[DEBUG] InitializeComponent
[DEBUG] Applying Fonts
[DEBUG] Getting AirportCyr
[DEBUG] Getting AkrobatSemiBold
[DEBUG] Getting AkrobatRegular
[DEBUG] Applying AkrobatRegular mainScreen to launcherStatusText
[DEBUG] Applying AirportCyr mainScreen to launcherStatusText
[DEBUG] Applying AkrobatRegular mainScreen to ServerStatusText
[DEBUG] Applying AirportCyr mainScreen to ServerStatusDesc
[DEBUG] Applying AkrobatSemiBold mainScreen to playProgressText
[DEBUG] Applying AkrobatRegular mainScreen to email
[DEBUG] Applying AkrobatSemiBold mainScreen to loginButton
[DEBUG] Applying AkrobatRegular mainScreen to password
[DEBUG] Applying AkrobatSemiBold mainScreen to rememberMe
[DEBUG] Applying AkrobatSemiBold mainScreen to forgotPassword
[DEBUG] Applying AkrobatSemiBold mainScreen to playProgressText
[DEBUG] Applying AkrobatSemiBold mainScreen to playButton
[DEBUG] Applying AkrobatSemiBold mainScreen to currentWindowInfo
[DEBUG] Applying AkrobatSemiBold mainScreen to imageServerName
[DEBUG] Applying AkrobatSemiBold mainScreen to registerAgree
[DEBUG] Applying AkrobatSemiBold mainScreen to registerCancel
[DEBUG] Applying AkrobatSemiBold mainScreen to settingsLanguageText
[DEBUG] Applying AkrobatSemiBold mainScreen to settingsQualityText
[DEBUG] Applying AkrobatSemiBold mainScreen to settingsSave
[DEBUG] Applying AkrobatSemiBold mainScreen to settingsGamePathText
[DEBUG] Applying AkrobatSemiBold mainScreen to wordFilterCheck
[DEBUG] Applying AkrobatSemiBold mainScreen to vFilesCheck
[DEBUG] Applying AkrobatSemiBold mainScreen to settingsGameFilesCurrent
[DEBUG] Applying AkrobatSemiBold mainScreen to logoutButton
[DEBUG] Applying AkrobatRegular mainScreen to registerEmail
[DEBUG] Applying AkrobatRegular mainScreen to registerPassword
[DEBUG] Applying AkrobatRegular mainScreen to registerConfirmPassword
[DEBUG] Applying AkrobatRegular mainScreen to registerTicket
[DEBUG] Applying AkrobatSemiBold mainScreen to registerButton
[DEBUG] Applying AkrobatSemiBold mainScreen to registerButton
[DEBUG] Applying AkrobatSemiBold mainScreen to registerText
[DEBUG] Applying cdnText mainScreen to settingsGamePathText
[DEBUG] Setting launcher location
[DEBUG] Launcher Location: 1947x525
[DEBUG] Disabling MaximizeBox
[DEBUG] Setting Styles
[DEBUG] Applying EventHandlers
[DEBUG] Checking permissions
[DEBUG] Checking InstallationDirectory
[DEBUG] Doing magic with imageServerName
[DEBUG] Setting ServerStatusBar
[DEBUG] Loading ModManager Cache
[DEBUG] Entering mainScreen_Load
[DEBUG] Updating server list
[DEBUG] Setting WindowName
[DEBUG] Checking window location
[DEBUG] _NFSW_Installation_Source is now http://cdn.worldunited.gg/gamefiles/packed/
[DEBUG] Applyinng ContextMenu
[DEBUG] Loading serverlist from: http://api.worldunited.gg/serverlist.json
[DEBUG] Setting server list
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 1095ms before attempting to connect again
[DEBUG] Loaded serverlist from: http://api.worldunited.gg/serverlist.json
[DEBUG] SERVERLIST: Checking...
[DEBUG] SERVERLIST: Setting first server in list
[DEBUG] SERVERLIST: Selected 1
[DEBUG] SERVERLIST: Checking if server is set on INI File
[DEBUG] SERVERLIST: Re-Checking if server is set on INI File
[DEBUG] SERVERLIST: Found something!
[DEBUG] SERVERLIST: Checking if server exists on our database
[DEBUG] SERVERLIST: Server found! Checking ID
[DEBUG] SERVERLIST: ID is 1
[DEBUG] SERVERLIST: ID set correctly
[DEBUG] SERVERLIST: Triggering server change
TRACE: Enqueue Command: DiscordRPC.RPC.Commands.PresenceCommand
[DEBUG] SERVERLIST: All done
[DEBUG] Checking for password
[DEBUG] Setting game language
[DEBUG] Setting texture quality
[DEBUG] Re-checking InstallationDirectory
[DEBUG] Hiding RegisterFormElements
[DEBUG] Hiding SettingsFormElements
[DEBUG] Hiding LoggedInFormElements
[DEBUG] Showing LoginFormElements
[DEBUG] Setting Registry Options
[ERROR] Object reference not set to an instance of an object
[DEBUG] Setting configurations
[DEBUG] Initializing DiscordRPC
[DEBUG] Initialize Downloading Process
ERR : Cannot Invoke client when AutomaticallyInvokeEvents has been set.
TRACE: Setting the connection state to DISCONNECTED
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(0)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to discord-ipc-0
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 2285ms before attempting to connect again
TRACE: Setting the connection state to DISCONNECTED
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(0)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to discord-ipc-0
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 3475ms before attempting to connect again
TRACE: Setting the connection state to DISCONNECTED
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(0)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to discord-ipc-0
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 4665ms before attempting to connect again
TRACE: Setting the connection state to DISCONNECTED
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(0)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to discord-ipc-0
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 5855ms before attempting to connect again
TRACE: Setting the connection state to DISCONNECTED
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(0)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to discord-ipc-0
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 7045ms before attempting to connect again
TRACE: Setting the connection state to DISCONNECTED
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(0)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to discord-ipc-0
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 8235ms before attempting to connect again
TRACE: Setting the connection state to DISCONNECTED
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(0)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to discord-ipc-0
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 9425ms before attempting to connect again
TRACE: Setting the connection state to DISCONNECTED
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(0)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to discord-ipc-0
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 10615ms before attempting to connect again
TRACE: Setting the connection state to DISCONNECTED
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(0)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to discord-ipc-0
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 11805ms before attempting to connect again
TRACE: Setting the connection state to DISCONNECTED
TRACE: Connecting to the pipe through the DiscordRPC.IO.ManagedNamedPipeClient
TRACE: ManagedNamedPipeClient.Connection(0)
TRACE: Connection Attempt 0 ()
INFO: Attempting to connect to discord-ipc-0
ERR : Failed connection to discord-ipc-0. The operation has timed out.
WARN: Tried to close a already closed pipe.
TRACE: Done. Result: True
TRACE: Skipping sandbox connection.
ERR : Failed to connect for some reason.
TRACE: Enqueued Message, but queue size is 0.
TRACE: Waiting 12995ms before attempting to connect again
Game is considered exited.
Initial process has exited.
All monitored processes have exited.
Exit with returncode 0
`

**Comment by ghost** [comment]
Seems like a firewall blocking connection. Will investigate and provide proper config for Linux

**Comment by ShayBox** [comment]
Was able to get to this today
![image](https://user-images.githubusercontent.com/9505196/85193158-08288a80-b294-11ea-9122-9407f63fabee.png)

**Comment by ghost** [comment]
Oh damn... I think i have to reinstall linux on one of my machines...

**Comment by ShayBox** [comment]
So any way to fix this? there's no servers

**Comment by ghost** [comment]
Working on it
