### ISSUE TITLE
Download Manager returned a Null Buffer

### ISSUE THREAD

**Issue by krateng** [SoapboxRaceWorld/GameLauncher_NFSW#41]
- **Launcher Version:** 2.1.0.6
- **Operating system:** Linux, 5.5.15-xanmod1 kernel
- **Antivirus/Firewall (if any):** -
- **Wine/Mono Version (if any):** lutris-nfsworld-5.4-x86_64

Regardless of selected CDN, after downloading the first 20 to 50 MB, I get "Failed to download gamefiles. Possible cause is that CDN went offline. Please select other CDN from Settings", then the download progress shows "Download Manager returned a Null Buffer". After restarting the launcher, progress is reset to zero. The game folder does get slightly bigger each time, but very slowly.

**Comment by ghost** [comment]
Try selecting different CDN Server
