### ISSUE TITLE
Can you add mac support?

### ISSUE THREAD

**Issue by AnonymousDeveloper4201337** [SoapboxRaceWorld/GameLauncher_NFSW#45]
That be awesome :D

**Comment by metonator** [comment]
Is compatible with Wine, you can try launching it with (for example) WineBottler.

**Comment by AnonymousDeveloper4201337** [comment]
Yes but if possible native support is always better than wine performance I already know about wine lol

**Comment by LeoCodes21** [comment]
not possible
