### ISSUE TITLE
I can't use my Logitech G29 Wheel

### ISSUE THREAD

**Issue by leillo1975** [SoapboxRaceWorld/GameLauncher_NFSW#45]
- **Launcher Version:*2.1.0.8* 
- **Operating system:*Ubuntu 20.04* 
- **Antivirus/Firewall (if any):*NO* 
- **Wine/Mono Version (if any):*lutris-nfsworld-5.4* 

Hello again. As I say on the issue title, I can't play the game with my Logitech G29 Wheel. If I connect it nothing occour when I move the direction and pedals.... but , with my wheel connected, if I use the keyboard keys, my wheel moves alone to right when I turn to left and the other way arround.
I don't have any problems with other games and this steering wheel model.

**Comment by ghost** [comment]
I really doubt if wine even can detect something that requires separate drivers to work.

**Comment by leillo1975** [comment]
With wine/proton I play rFactor2, automobilista, Assetto Corsa, Euro Truck Simulator 2, Dirt Rally, .... This is not the problem. A basic driver is included on the Linux kernel, but I've installed a more complete module on my system (https://github.com/berarma/new-lg4ff).
