### ISSUE TITLE
Critical Error

### ISSUE THREAD

**Issue by rjshooter06** [SoapboxRaceWorld/GameLauncher_NFSW#46]
Launcher Version: 2.1.0.8
Operating system: Win 7 SP 1
Antivirus/Firewall (if any): Avast Antivirus
Wine/Mono Version (if any): Nope

Critical Error, here's the file report

[Bug Report.zip](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/4681707/Bug.Report.zip)

**Comment by Zacam** [comment]
That's a game files execution of NFSW.exe; not a launcher problem.

Like the AntiVirus is interfering considering its crashing out "Access violation reading location 0x00000008"  which is an extremely low value. Either attempt to make there be an exception/exclusion to the GameLauncher and nfsw EXE's (and the folders they are in) so they can be ignored, or try exiting AntiVirus entirely to test if the game will then launch.

"MSVCR90.dll" is also mentioned, so make sure you have the "Microsoft Visual C++ Runtimes 2015-2019 (x86)" installed.

Either way: This is not a Launcher problem.
