### ISSUE TITLE
Nao consigo baixar

### ISSUE THREAD

**Issue by nenegresco007** [SoapboxRaceWorld/GameLauncher_NFSW#48]
entro no laucher e ele começa a baixar o game mas chega em 87mega e trava, e nao baixa mais, alguem pode me ajudar???

**Comment by Zacam** [comment]
Try not downloading the game files to the same folder that GameLauncher.exe is in.
If you are already downloading the game files to an already empty/new folder; then check AntiVirus or Firewall or wireless (if used) router; as that sounds like a connection problem.

(Google Translate):
Tente não baixar os arquivos do jogo para a mesma pasta em que GameLauncher.exe está.
Se você já está baixando os arquivos do jogo para uma pasta já vazia / nova; depois verifique seu antivírus, firewall ou roteador sem fio (se usado); pois isso parece um problema de conexão.
