### ISSUE TITLE
You should use crc32 for validating the game data files.

### ISSUE THREAD

**Issue by alex4o** [SoapboxRaceWorld/GameLauncher_NFSW#49]
Because it is way faster, and you don't realy need cryptographicly safe hash function. 
https://github.com/force-net/Crc32.NET
https://docs.oracle.com/javase/7/docs/api/java/util/zip/CRC32.html

**Comment by LeoCodes21** [comment]
Good idea, I'll look into this when we implement [SpeedLoad](https://github.com/SoapboxRaceWorld/SpeedLoad). The current downloader code isn't really modification-friendly.
