### ISSUE TITLE
Game Launcher crashed

### ISSUE THREAD

**Issue by kinesight** [SoapboxRaceWorld/GameLauncher_NFSW#50]
I just downloaded the latest launcher today. I opened the launcher - the download of the game went to 67% then the app crashed , I clicked continue and it closed the program. Afterwhich I relaunched the Launcher and the download restarted instead of continuing from where it left of ?

It's got 1.05GB of the game downloaded but it wants to redownload from the start?

**Comment by ghost** [comment]
Can you provide an error message?

**Comment by Zacam** [comment]
Also make sure that the GameLauncher is not trying to download directly to the same folder that the GameLaucher.exe itself is in. It should either be a separate empty folder, or a sub-folder so it won't try to put the GameLauncher.exe and nfsw.exe together.
