### ISSUE TITLE
Framerate Locked

### ISSUE THREAD

**Issue by CircuitLord** [SoapboxRaceWorld/GameLauncher_NFSW#51]
The framerate seems to be locked at 50 for me. I don't know if that's just a predefined setting, or if the whole game revolves around running at that framerate, but if it isn't, it would be really nice to have an unlocked framerate, or at least the full 60.

Let me know if you have any more questions, thanks so much for even making this possible in the first place :)

**Comment by LeoCodes21** [comment]
Try to turn off vsync. That's what usually locks the frame rate.

**Comment by CircuitLord** [comment]
Hm, let me look at that.

**Comment by CircuitLord** [comment]
Yep, I was just dumb and didn't turn that off, now I get a slightly overkill 240fps. Thanks :)

**Comment by LeoCodes21** [comment]
No problem! Glad I could help.
