### ISSUE TITLE
I FORGOT MY PASSWORD

### ISSUE THREAD

**Issue by YannKX** [SoapboxRaceWorld/GameLauncher_NFSW#53]
I click on "I forgot my password" but warn that the email is invalid

P.S : 
6 months or 7 months ago I created this account and stopped playing, I came back today
PLEASE HELP ME !

**Comment by Nevada789** [comment]
Not a problem with the launcher, go to the server discord that corrosponds to the server you're talking about. 
World United
https://discord.gg/Sv3zT9A

Power Servers:
WOPL Reborn
https://discord.gg/6rpWwss
NightRiderz
https://discord.gg/aJ8VxP5
World Evolved V2
https://discord.gg/8cwZZqg

Test Servers:
Freeroam Sparkserver
https://discord.gg/dqvFpFw

Community Servers:
Zesty's
https://discord.gg/gJyXwRZ
NFSW Community Hub
https://discord.gg/Q7vg7Ny
 Underground Stage
https://discord.gg/3W84jg8
