### ISSUE TITLE
Decomression Returned 1

### ISSUE THREAD

**Issue by Quinnerfire** [SoapboxRaceWorld/GameLauncher_NFSW#54]
- **Launcher Version:** Latests (1.9.1.28. and 29.)
- **Operating system:** Win 10
- **Antivirus/Firewall (if any):** Avast
- **Wine/Mono Version (if any):** -

**Issue: I have managed to install for the first time, I've also played a couple minutes and I decided to re-install it in an other directory. Since than it's not working. I have tried to re-locate the installation folder and I also tried to install the game with the 1.9.1.29. version too, but same issue.**

Error description goes here
While the game is installing an error msg: "decompression returned 1" pops up, and this is the following:
![error](https://user-images.githubusercontent.com/39460757/40279660-92f2f606-5c46-11e8-9abc-7f09f1cd778a.png)   ...

**Comment by metonator** [comment]
Just relaunch launcher

**Comment by Quinnerfire** [comment]
I had to restart it a few more times, but it did the job. I appreciate your help.
