### ISSUE TITLE
Dead part on game screen

### ISSUE THREAD

**Issue by TOMASSANTOS14** [SoapboxRaceWorld/GameLauncher_NFSW#55]
- **2.1.2.4** 
- **Windows 10** 
- **Antivirus none:** 

I have a dead part in my game screen, where my mouse pointer changes to the windows one and I can't click on anything, for example, I can't go to the car dealer.

thanks,
Tomás Santos

**Comment by Nevada789** [comment]
The solution to this is to use windowed mode.

**Comment by TOMASSANTOS14** [comment]
How do I Put the game on windowed Mode? Sorry, I don't know.

A quarta, 17 de jun de 2020, 21:44, Nevada S <notifications@github.com>
escreveu:

**Comment by TOMASSANTOS14** [comment]
Ok, I found it, thank you very much.

A quarta, 17 de jun de 2020, 21:44, Nevada S <notifications@github.com>
escreveu:
