### ISSUE TITLE
Starting the game and it crashes

### ISSUE THREAD

**Issue by hokohpops** [SoapboxRaceWorld/GameLauncher_NFSW#55]
- **Launcher Version:** 1.9.1.31
- **Operating system:** Windows 10 (64 bit)
- **Antivirus/Firewall (if any):** Norton
- **Wine/Mono Version (if any):** ---

**Description of issue:**
```
Startup crashes, whenever i opened the program, signed in and clicked on play now, the game loads as usual but then it crashes with a pop up of windows saying the program isn't responding. It has occurred everytime i tried to play this game and i have installed the latest version of java. Is there a way to solve this?
Thanks
```

**JIT Error (if any)**
```
---
```

**Comment by metonator** [comment]
Do other  games runs without any issue?

**Comment by hokohpops** [comment]
The previous version of this game did run but it was all of a sudden started to crash ever since the update

Thanks
Ho Koh
Student number: 1036 2372

________________________________

**Comment by metonator** [comment]
Can you try to downgrade and see if the issue is there? the only change i did is in fact bootflow.gfx related (aka intro screen)

**Comment by hokohpops** [comment]
How do I downgrade?

Thanks
Ho Koh
Student number: 1036 2372

________________________________

**Comment by metonator** [comment]
Just download older tag, ie: https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/releases/tag/1.9.1.30

**Comment by hokohpops** [comment]
It worked. Cheers!

Thanks
Ho Koh
Student number: 1036 2372

________________________________

**Comment by metonator** [comment]
still have to find why...
