### ISSUE TITLE
unhandled exception 

### ISSUE THREAD

**Issue by danger14231** [SoapboxRaceWorld/GameLauncher_NFSW#56]
- **Launcher Version:** 2.1.2.4
- **Operating system:** windows 10 64-bit
- **Antivirus/Firewall (if any):** i think windows defender
- **Wine/Mono Version (if any):** 
Detail sections says:
Application does not support just-in-time (JIT)
debugging. See the end of this message for details.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at GameLauncher.App.Classes.GPU.GPUHelper.CardName()
   at GameLauncher.MainScreen..ctor()
   at GameLauncher.Program.Main()

************** Loaded Assemblies **************

----------------------------------------
GameLauncher
    Assembly Version: 2.1.2.4
    Win32 Version: 2.1.2.4
    CodeBase: file:///C:/NFS%20World/GameLauncher.exe
----------------------------------------

----------------------------------------

----------------------------------------

----------------------------------------

----------------------------------------
Newtonsoft.Json
    Assembly Version: 12.0.0.0
    Win32 Version: 12.0.3.23909
    CodeBase: file:///C:/NFS%20World/Newtonsoft.Json.DLL
----------------------------------------

----------------------------------------

----------------------------------------

----------------------------------------
Nancy.Hosting.Self
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/NFS%20World/Nancy.Hosting.Self.DLL
----------------------------------------
Nancy
    Assembly Version: 2.0.0.0
    Win32 Version: 2.0.0.0
    CodeBase: file:///C:/NFS%20World/Nancy.DLL
----------------------------------------

----------------------------------------

----------------------------------------

----------------------------------------

----------------------------------------
DiscordRPC
    Assembly Version: 1.0.150.0
    Win32 Version: 1.0.150.0
    CodeBase: file:///C:/NFS%20World/DiscordRPC.DLL
----------------------------------------
Microsoft.WindowsAPICodePack.Shell
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/NFS%20World/Microsoft.WindowsAPICodePack.Shell.DLL
----------------------------------------
Microsoft.WindowsAPICodePack
    Assembly Version: 1.1.0.0
    Win32 Version: 1.1.0.0
    CodeBase: file:///C:/NFS%20World/Microsoft.WindowsAPICodePack.DLL
----------------------------------------

----------------------------------------

----------------------------------------

************** JIT Debugging **************
Application does not support Windows Forms just-in-time (JIT)
debugging. Contact the application author for more
information.

**Comment by ghost** [comment]
@Zacam that one is yours

**Comment by Zacam** [comment]
Resolved on SBRW Discord.
The iGPU had no driver installed to present it as a "Display Adapter" in windows, and no discreet GPU adapter present.
Found the correct drivers for the processor and got them installed, GameLauncher was able to proceed with the rest of 1st Run and into game server.
