### ISSUE TITLE
Need help!

### ISSUE THREAD

**Issue by Zpewg** [SoapboxRaceWorld/GameLauncher_NFSW#57]
- **Launcher Version:** 1.9.1.31
- **Operating system:** Windows 10 Pro
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 

**Description of issue:**I install the game but when i open the launcher it blocks at 8,00 mb /1,05 GB
```
Error description goes here
```

**JIT Error (if any)**
```
Please embed it inside code tag. Otherwise, delete this line or just type "none"
```

**Comment by metonator** [comment]
Just wait for SpeedLoad to be implemented, meanwhile you can download and extract files from link on discord.
