### ISSUE TITLE
Backup Server List URLs not live & Additional Backup URL Proposal

### ISSUE THREAD

**Issue by DavidCarbon** [SoapboxRaceWorld/GameLauncher_NFSW#58]
## Current Issue

teststuff.worldonline.pl & api.nightriderz.world currently doesn't have the serverlist.json or servers.json file on their respective servers.

https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/blob/0878f61055ca05592a8e3e88ca13c47e4ae5ebff/GameLauncher/App/Classes/Self.cs#L19-L23

## Additional Backup URL Proposal
I want to submit an additional Backup for serverlist and cdn_list.
- http://api-sbrw.davidcarbon.download/

This static API will host these files and be updated when the Main API updates its files as well. This also follows the format on Main API Server 
- http://api-sbrw.davidcarbon.download/serverlist.json
- http://api-sbrw.davidcarbon.download/cdn_list.json

**Comment by ghost** [comment]
Done.
