### ISSUE TITLE
LOGIN ERROR on each start

### ISSUE THREAD

**Issue by GitMensch** [SoapboxRaceWorld/GameLauncher_NFSW#61]
- **Launcher Version:** 1.9.33 (older versions had the same problem)
- **Operating system:** Win10

**Description of issue:**

* starting launcher
* enter login data
* click login
* see the "welcome back" message
* click play
```
---------------------------
GameLauncher
---------------------------
LOGIN ERROR
---------------------------
OK   
---------------------------
```
* press OK (launcher waits until this is done)
* game starts

Is there any option to fix this false-positive? Does anyone else have this error? Can I provide more details? Is there any option to have "NFSWO_COMMUNICATION_LOG.txt" as an actual text file?

**Comment by Flori1n** [comment]
yes

**Comment by Flori1n** [comment]
not work

**Comment by Flori1n** [comment]
this mesaje is 2018 07 18 15:29

**Comment by metonator** [comment]
The best would be to provide server aswell, so i can "debug" more

**Comment by metonator** [comment]
@Flori1n if you have "date" as message, then it means you got banned.

**Comment by GitMensch** [comment]
@metonator The error happens both with Apex and World Online (*after* clicking "Play" [Login works, the game starts successful after I press "OK" on the error message])

**Comment by metonator** [comment]
Can't reproduce that. Do any of you uses wireshark and can check "authenticateUser" calls?

**Comment by metonator** [comment]
i mean, once user logged in, and game was still downloading, the "play now" was supposed to re-trigger login. seems like this fails actually.

**Comment by metonator** [comment]
https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/releases/tag/1.9.1.35

**Comment by GitMensch** [comment]
Fixed.
