### ISSUE TITLE
First Time Select Game Server, Displays Server List Twice

### ISSUE THREAD

**Issue by DavidCarbon** [SoapboxRaceWorld/GameLauncher_NFSW#61]
- **Launcher Version:** Development Build (GitHub Branch)
- **Operating system:** Windows 10

With backup Server being Implemented the First time Select a Server displays Server List twice.
![image](https://user-images.githubusercontent.com/9911250/85090297-9ec45100-b199-11ea-82e0-4aefae00c15d.png)
This does not affect the main Server List. 
![image](https://user-images.githubusercontent.com/9911250/85090526-3033c300-b19a-11ea-99a2-80f3fb9a6ba4.png)

**Comment by ghost** [comment]
Working on a fix.

**Comment by ghost** [comment]
Fixed.
