### ISSUE TITLE
GAME LAUNCHER NOT WORKING

### ISSUE THREAD

**Issue by TONTO78** [SoapboxRaceWorld/GameLauncher_NFSW#62]
Iv'e downloaded latest version of nfsw game launcher every time iv'e tried to run it ,it says game launcher has stopped working 

please help me with this im really lookin forward to playing game

**Comment by Zacam** [comment]
Are you running it "As Administrator"?
A screenshot or text output from a "More Details" or "More Info" screen option (if available) would help.
