### ISSUE TITLE
There is a trojan virus when i attempted to download

### ISSUE THREAD

**Issue by Adam123341** [SoapboxRaceWorld/GameLauncher_NFSW#63]
- CURRENT VERSION: 1.9.1.35
- Windows 10 Pro

Trojan:Win32/Zpevdo.A was detected in the file for the game
```
Windows Defender detected a trojan virus known as Trojan:Win32/Zpevdo.A.
```

```

```

**Comment by metonator** [comment]
Can you check which file exactly?

**Comment by Adam123341** [comment]
The file is the main launcher zip folder

**Comment by Caserol23** [comment]
please temporarily disable your antivirus to continue launching the game...
