### ISSUE TITLE
Game can't start

### ISSUE THREAD

**Issue by Clem0908** [SoapboxRaceWorld/GameLauncher_NFSW#63]
- **Launcher Version:** 2.1.2.6
- **Operating system:** Ubuntu 20.04
- **Antivirus/Firewall (if any):** None
- **Wine/Mono Version (if any):** lutris-nfsworld-5.4-x86_64

When I hit "Play now" button I get the following message : 

Application does not support just-in-time (JIT)\ndebugging. See the end of this message for details.\n\n************** Exception Text **************\nSystem.Exception: .links file includes nonexistent file: Z:\media\Disk_1_1To\Need_for_Speed_World\Game\CARS\GlobalC.lzc
  at GameLauncher.MainScreen.CleanLinks (System.String linksPath) [0x000be] in <7933fe61ac734670939e6a149912573e>:0 
  at GameLauncher.MainScreen.playButton_Click (System.Object sender, System.EventArgs e) [0x001fd] in <7933fe61ac734670939e6a149912573e>:0 
  at System.Windows.Forms.Control.OnClick (System.EventArgs e) [0x0001a] in <4055c35822884d58876b1c889fdafb80>:0 
  at System.Windows.Forms.Button.OnClick (System.EventArgs e) [0x00039] in <4055c35822884d58876b1c889fdafb80>:0 
  at System.Windows.Forms.Button.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x0008e] in <4055c35822884d58876b1c889fdafb80>:0 
  at System.Windows.Forms.Control.WmMouseUp (System.Windows.Forms.Message& m, System.Windows.Forms.MouseButtons button, System.Int32 clicks) [0x001b6] in <4055c35822884d58876b1c889fdafb80>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x005a0] in <4055c35822884d58876b1c889fdafb80>:0 
  at System.Windows.Forms.ButtonBase.WndProc (System.Windows.Forms.Message& m) [0x0011f] in <4055c35822884d58876b1c889fdafb80>:0 
  at System.Windows.Forms.Button.WndProc (System.Windows.Forms.Message& m) [0x00056] in <4055c35822884d58876b1c889fdafb80>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.OnMessage (System.Windows.Forms.Message& m) [0x00001] in <4055c35822884d58876b1c889fdafb80>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x000b9] in <4055c35822884d58876b1c889fdafb80>:0 
  at System.Windows.Forms.NativeWindow.Callback (System.IntPtr hWnd, Interop+User32+WindowMessage msg, System.IntPtr wparam, System.IntPtr lparam) [0x00030] in <4055c35822884d58876b1c889fdafb80>:0 

\n************** Loaded Assemblies **************\nmscorlib\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/4.5/mscorlib.dll\n----------------------------------------\nGameLauncher\n    Assembly Version: 2.1.2.6\n    Win32 Version: 2.1.2.6\n    CodeBase: file:///Z:/media/Disk_1_1To/Need_for_Speed_World/Launcher/GameLauncher.exe\n----------------------------------------\nSystem\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll\n----------------------------------------\nSystem.Windows.Forms\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Windows.Forms/4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll\n----------------------------------------\nINIFileParser\n    Assembly Version: 2.5.2.0\n    Win32 Version: 2.5.2\n    CodeBase: file:///Z:/media/Disk_1_1To/Need_for_Speed_World/Launcher/INIFileParser.dll\n----------------------------------------\nNewtonsoft.Json\n    Assembly Version: 12.0.0.0\n    Win32 Version: 12.0.3.23909\n    CodeBase: file:///Z:/media/Disk_1_1To/Need_for_Speed_World/Launcher/Newtonsoft.Json.dll\n----------------------------------------\nSystem.Core\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll\n----------------------------------------\nNancy.Hosting.Self\n    Assembly Version: 2.0.0.0\n    Win32 Version: 2.0.0.0\n    CodeBase: file:///Z:/media/Disk_1_1To/Need_for_Speed_World/Launcher/Nancy.Hosting.Self.dll\n----------------------------------------\nSystem.Drawing\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Drawing/4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll\n----------------------------------------\nAccessibility\n    Assembly Version: 4.0.0.0\n    Win32 Version: \n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/Accessibility/4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll\n----------------------------------------\nDiscordRPC\n    Assembly Version: 1.0.150.0\n    Win32 Version: 1.0.150.0\n    CodeBase: file:///Z:/media/Disk_1_1To/Need_for_Speed_World/Launcher/DiscordRPC.dll\n----------------------------------------\nSystem.Configuration\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Configuration/4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll\n----------------------------------------\nSystem.Xml\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll\n----------------------------------------\nMono.Security\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.0.0.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll\n----------------------------------------\nI18N\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.0.0.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/I18N/4.0.0.0__0738eb9f132ed756/I18N.dll\n----------------------------------------\nI18N.West\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.0.0.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/I18N.West/4.0.0.0__0738eb9f132ed756/I18N.West.dll\n----------------------------------------\nNancy\n    Assembly Version: 2.0.0.0\n    Win32 Version: 2.0.0.0\n    CodeBase: file:///Z:/media/Disk_1_1To/Need_for_Speed_World/Launcher/Nancy.dll\n----------------------------------------\nFlurl\n    Assembly Version: 2.8.2.0\n    Win32 Version: 2.8.2.0\n    CodeBase: file:///Z:/media/Disk_1_1To/Need_for_Speed_World/Launcher/Flurl.dll\n----------------------------------------\nSystem.Net.Http\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Net.Http/4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll\n----------------------------------------\nSystem.Management\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Management/4.0.0.0__b03f5f7f11d50a3a/System.Management.dll\n----------------------------------------\nFlurl.Http\n    Assembly Version: 2.4.2.0\n    Win32 Version: 2.4.2.0\n    CodeBase: file:///Z:/media/Disk_1_1To/Need_for_Speed_World/Launcher/Flurl.Http.dll\n----------------------------------------\nMicrosoft.WindowsAPICodePack\n    Assembly Version: 1.1.0.0\n    Win32 Version: 1.1.0.0\n    CodeBase: file:///Z:/media/Disk_1_1To/Need_for_Speed_World/Launcher/Microsoft.WindowsAPICodePack.dll\n----------------------------------------\nAnonymously Hosted DynamicMethods Assembly\n    Assembly Version: 0.0.0.0\n    Win32 Version: n/a\n    CodeBase: \n----------------------------------------\nMicrosoft.CSharp\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/Microsoft.CSharp/4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll\n----------------------------------------\nMicrosoft.WindowsAPICodePack.Shell\n    Assembly Version: 1.1.0.0\n    Win32 Version: 1.1.0.0\n    CodeBase: file:///Z:/media/Disk_1_1To/Need_for_Speed_World/Launcher/Microsoft.WindowsAPICodePack.Shell.dll\n----------------------------------------\nPresentationFramework\n    Assembly Version: 3.0.0.0\n    Win32 Version: 3.0.6920.5738 built by: QFE\n    CodeBase: file:///Z:/media/Disk_1_1To/Need_for_Speed_World/Launcher/PresentationFramework.dll\n----------------------------------------\nPresentationCore\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C\n    CodeBase: file:///Z:/media/Disk_1_1To/Need_for_Speed_World/Launcher/PresentationCore.dll\n----------------------------------------\nWindowsBase\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.0.0.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/WindowsBase/4.0.0.0__31bf3856ad364e35/WindowsBase.dll\n----------------------------------------\nSystem.Numerics\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Numerics/4.0.0.0__b77a5c561934e089/System.Numerics.dll\n----------------------------------------\nSystem.Runtime.Serialization\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Runtime.Serialization/4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll\n----------------------------------------\nSystem.Data\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Data/4.0.0.0__b77a5c561934e089/System.Data.dll\n----------------------------------------\n\n************** JIT Debugging **************\nApplication does not support Windows Forms just-in-time (JIT)\ndebugging. Contact the application author for more\ninformation.\n

**Comment by ghost** [comment]
please delete .links and .data folder from nfsw installation directory

**Comment by Clem0908** [comment]
Done and still don't work

**Comment by snitra** [comment]
same no work

**Comment by ghost** [comment]
> same no work



> Done and still don't work

u need still help? Im solved this problem by my side..... tell me if u need help...

**Comment by Clem0908** [comment]
Yes, please ! :)

**Comment by ghost** [comment]
> 
> 
> Yes, please ! :)

Im downloaded WINE runtime from official wine site (https://dl.winehq.org/wine/wine-mono/)
Lutris-NFSW-RIGHT CLICK-Controll Panel-Install Program and chosse downloaded runtime....Maybe im didnt write all steps corrently because Im didnt remember all and im not Linux user right now sorry. :)

**Comment by Clem0908** [comment]
Thanks :)

**Comment by ghost** [comment]
NP 👍

**Comment by ghost** [comment]
> 
> 
> Thanks :)

Game running succesfully?
