### ISSUE TITLE
Trojan ? Help please

### ISSUE THREAD

**Issue by Numik** [SoapboxRaceWorld/GameLauncher_NFSW#65]
- **Launcher Version: 1.9.1.35
- **Operating system: Windows 10 Pro 64-bit
- **Antivirus/Firewall (if any): Windows Defender
- **Wine/Mono Version (if any):** 

**Description of issue: Trojan Zpevdo.A , and the GameLauncher gets deleted asap as i extract it ...

```
Error description goes here
```

**JIT Error (if any)**
```
Please embed it inside code tag. Otherwise, delete this line or just type "none"
```

**Comment by 1DavidCarbon** [comment]
Temporarily disable your antivirus, in order to extract launcher and to launch the game. When possible add it to exclusion, in your antivirus. The flag is a false positive.
