### ISSUE TITLE
Game keep crashing after v2.1.2.7build-A008BC8 update.

### ISSUE THREAD

**Issue by CougarYap** [SoapboxRaceWorld/GameLauncher_NFSW#66]
I'm new to Github,created account just to post issues.(maybe)

After I updated the launcher to v2.1.2.7build-A008BC8 ,everything looks fine,some minutes later after any races,the game froze and not responding,heads-up display is gone. I can't even force close the game,I can open task manager but the game is blocking it,I have to sign out and sign in again to close it.

**Comment by ghost** [comment]
Are you sure is not a PC issue at this point? For me it looks like HDD being overused and system keeps retrying to read something that cant be readed.
