### ISSUE TITLE
erro de cdn

### ISSUE THREAD

**Issue by Jailtex** [SoapboxRaceWorld/GameLauncher_NFSW#67]
toda vez que inicio o donwload do game no launcher da um erro de cdn offline
![Capturar](https://user-images.githubusercontent.com/67338336/85442252-5aa0ca00-b566-11ea-8873-444d7f5b7d38.PNG)

**Comment by ghost** [comment]
Which CDN are you actually using?

**Comment by ghost** [comment]
Or, make sure other CDNs have the same issue.

**Comment by davibr1** [comment]
the same problem are happening to me what i need to do?
