### ISSUE TITLE
newtonsoft.json keeps flashing and annoying!

### ISSUE THREAD

**Issue by nIkola42** [SoapboxRaceWorld/GameLauncher_NFSW#68]
- **Launcher Version:** 
- **Operating system:** 
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 

**Description of issue:**
```
Error description goes here
```

**JIT Error (if any)**
```
Please embed it inside code tag. Otherwise, delete this line or just type "none"
```

**Comment by nIkola42** [comment]
why did u close this

**Comment by nIkola42** [comment]
10/10 will never play again....

**Comment by metonator** [comment]
i closed it because "no logs", "no info", nothing, nada, null, 0, ... actually blackhole
