### ISSUE TITLE
Error in HWID.cs -> FingerPrint.identifier(string, string); with suggested fix

### ISSUE THREAD

**Issue by GustavoDill** [SoapboxRaceWorld/GameLauncher_NFSW#69]
- **Launcher Version: 2.1.3.0** 
- **Operating system: Windows 10 Pro** 
- **Antivirus/Firewall (if any): Windows Defender Antivirus and Firewall** 
- **Wine/Mono Version (if any):** 

In this image is marked a error in the code.
![image](https://user-images.githubusercontent.com/43525892/85476788-66ed4d00-b58f-11ea-9a39-98eb4c53f462.png)

The marked code in the image is problematic because the *mo[wmiProperty]* object cannot call the method .ToString() if it is null, resulting in an exception.

The fix i made is:
![image](https://user-images.githubusercontent.com/43525892/85476581-06f6a680-b58f-11ea-9258-d9cdc55c1247.png)
This simple fix just check if the result of *mo[wmiProperty]* is null, if not then call .ToString() method, otherwise it just continues the loop.

NOTE: The same issue was present in the previous version of the launcher.

**Comment by ghost** [comment]
Thanks, will update on next code session. (2/2)

**Comment by GustavoDill** [comment]
I'm glad i could help!
