### ISSUE TITLE
Error in MainScreen.cs -> mainScreen_Load(object, EventArgs);

### ISSUE THREAD

**Issue by GustavoDill** [SoapboxRaceWorld/GameLauncher_NFSW#70]
- **Launcher Version: 2.1.3.0** 
- **Operating system: Windows 10 Pro** 
- **Antivirus/Firewall (if any): Windows Defender Antivirus and Firewall** 
- **Wine/Mono Version (if any):** 

Is this part of the code (currently lines 705-706)
![image](https://user-images.githubusercontent.com/43525892/85478434-9baed380-b592-11ea-82f5-d9296234ee08.png)
The `Registry.GetValue()` method cannot call `.ToString()` if its result is null;

Suggest fix
![image](https://user-images.githubusercontent.com/43525892/85478469-b123fd80-b592-11ea-9513-9653f245aeba.png)
As the if checks the parameters from the first to last we can use the OR operator to null check the variable and call `gameInstallDirValue.ToString()` inside the if statement after the null check

**Comment by ghost** [comment]
Thanks, will update on next code session. (1/2)

**Comment by GustavoDill** [comment]
I'm glad i could help!
