### ISSUE TITLE
download failed decompression returned 1

### ISSUE THREAD

**Issue by SHINGOvtec** [SoapboxRaceWorld/GameLauncher_NFSW#71]
- **Launcher Version:** 
- **Operating system:** 
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):** 

**Description of issue:**
```
Error description goes here
```

**JIT Error (if any)**
```
Please embed it inside code tag. Otherwise, delete this line or just type "none"
```

**Comment by metonator** [comment]
Not enough info
