### ISSUE TITLE
Why is happening ?

### ISSUE THREAD

**Issue by YannKX** [SoapboxRaceWorld/GameLauncher_NFSW#71]
- **Launcher Version:** 2.1.3.0
- **Operating system:** Linux Mint
The graphics look like this
https://imgur.com/NrNt2M9
i'm new user of the linux system

**Comment by czeckpage** [comment]
Hello Im too Linux user (KDE neon) and im didnt start this game im mean a this game didnt start on my pc...
Pls tell me how u run this game on Linux.

**Comment by ghost** [comment]
Make sure that drivers are installed, it looks like that is using opensource drivers instead of propetary

**Comment by czeckpage** [comment]
> Make sure that drivers are installed, it looks like that is using opensource drivers instead of propetary

Hello im have a problem with run this game... Im using KDE neon 

Application does not support just-in-time (JIT)\ndebugging. See the end of this message for details.\n\n************** Exception Text **************\nSystem.Net.WebException: The request was canceled
  at System.Net.WebOperation.CheckThrowDisposed (System.Boolean throwIt, System.Runtime.ExceptionServices.ExceptionDispatchInfo& field) [0x00029] in <f508ff7dc2d3475abfc25b6b60600edf>:0 
  at System.Net.WebOperation.ThrowIfClosedOrDisposed (System.Threading.CancellationToken cancellationToken) [0x00011] in <f508ff7dc2d3475abfc25b6b60600edf>:0 
  at System.Net.WebOperation.ThrowIfClosedOrDisposed () [0x00006] in <f508ff7dc2d3475abfc25b6b60600edf>:0 
  at System.Net.WebConnectionStream.Read (System.Byte[] buffer, System.Int32 offset, System.Int32 count) [0x00019] in <f508ff7dc2d3475abfc25b6b60600edf>:0 
  at System.IO.StreamReader.ReadBuffer () [0x00028] in <a1336bab325642fd867e87ca7626bada>:0 
  at System.IO.StreamReader.ReadToEnd () [0x00059] in <a1336bab325642fd867e87ca7626bada>:0 
  at GameLauncher.App.Classes.Auth.ClassicAuth.Login (System.String email, System.String password) [0x0008d] in <a7cc4675c59a48f185ec4ff414bec82c>:0 
  at GameLauncher.MainScreen.loginButton_Click (System.Object sender, System.EventArgs e) [0x000f8] in <a7cc4675c59a48f185ec4ff414bec82c>:0 
  at System.Windows.Forms.Control.OnClick (System.EventArgs e) [0x0001f] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Button.OnClick (System.EventArgs e) [0x00037] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Button.OnMouseUp (System.Windows.Forms.MouseEventArgs mevent) [0x0009a] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Control.WmMouseUp (System.Windows.Forms.Message& m, System.Windows.Forms.MouseButtons button, System.Int32 clicks) [0x001c3] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Control.WndProc (System.Windows.Forms.Message& m) [0x005a0] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.ButtonBase.WndProc (System.Windows.Forms.Message& m) [0x0011f] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Button.WndProc (System.Windows.Forms.Message& m) [0x00056] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.OnMessage (System.Windows.Forms.Message& m) [0x00001] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.Control+ControlNativeWindow.WndProc (System.Windows.Forms.Message& m) [0x000b3] in <afc71676634a41889c6929c14e8a57bd>:0 
  at System.Windows.Forms.NativeWindow.Callback (System.IntPtr hWnd, System.Int32 msg, System.IntPtr wparam, System.IntPtr lparam) [0x00030] in <afc71676634a41889c6929c14e8a57bd>:0 

\n************** Loaded Assemblies **************\nmscorlib\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/4.5/mscorlib.dll\n----------------------------------------\nGameLauncher\n    Assembly Version: 2.1.3.0\n    Win32 Version: 2.1.3.0\n    CodeBase: file:///Z:/home/daniel/Games/soapbox-race-world-need-for-speed-world/GameLauncher.exe\n----------------------------------------\nSystem\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System/4.0.0.0__b77a5c561934e089/System.dll\n----------------------------------------\nSystem.Windows.Forms\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Windows.Forms/4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll\n----------------------------------------\nINIFileParser\n    Assembly Version: 2.5.2.0\n    Win32 Version: 2.5.2\n    CodeBase: file:///Z:/home/daniel/Games/soapbox-race-world-need-for-speed-world/INIFileParser.dll\n----------------------------------------\nNewtonsoft.Json\n    Assembly Version: 12.0.0.0\n    Win32 Version: 12.0.3.23909\n    CodeBase: file:///Z:/home/daniel/Games/soapbox-race-world-need-for-speed-world/Newtonsoft.Json.dll\n----------------------------------------\nSystem.Core\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Core/4.0.0.0__b77a5c561934e089/System.Core.dll\n----------------------------------------\nNancy.Hosting.Self\n    Assembly Version: 2.0.0.0\n    Win32 Version: 2.0.0.0\n    CodeBase: file:///Z:/home/daniel/Games/soapbox-race-world-need-for-speed-world/Nancy.Hosting.Self.dll\n----------------------------------------\nSystem.Drawing\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Drawing/4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll\n----------------------------------------\nAccessibility\n    Assembly Version: 4.0.0.0\n    Win32 Version: \n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/Accessibility/4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll\n----------------------------------------\nDiscordRPC\n    Assembly Version: 1.0.150.0\n    Win32 Version: 1.0.150.0\n    CodeBase: file:///Z:/home/daniel/Games/soapbox-race-world-need-for-speed-world/DiscordRPC.dll\n----------------------------------------\nSystem.Configuration\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Configuration/4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll\n----------------------------------------\nSystem.Xml\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Xml/4.0.0.0__b77a5c561934e089/System.Xml.dll\n----------------------------------------\nMono.Security\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.0.0.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/Mono.Security/4.0.0.0__0738eb9f132ed756/Mono.Security.dll\n----------------------------------------\nI18N\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.0.0.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/I18N/4.0.0.0__0738eb9f132ed756/I18N.dll\n----------------------------------------\nI18N.Rare\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.0.0.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/I18N.Rare/4.0.0.0__0738eb9f132ed756/I18N.Rare.dll\n----------------------------------------\nNancy\n    Assembly Version: 2.0.0.0\n    Win32 Version: 2.0.0.0\n    CodeBase: file:///Z:/home/daniel/Games/soapbox-race-world-need-for-speed-world/Nancy.dll\n----------------------------------------\nFlurl\n    Assembly Version: 2.8.2.0\n    Win32 Version: 2.8.2.0\n    CodeBase: file:///Z:/home/daniel/Games/soapbox-race-world-need-for-speed-world/Flurl.dll\n----------------------------------------\nSystem.Net.Http\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Net.Http/4.0.0.0__b03f5f7f11d50a3a/System.Net.Http.dll\n----------------------------------------\nSystem.Management\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Management/4.0.0.0__b03f5f7f11d50a3a/System.Management.dll\n----------------------------------------\nFlurl.Http\n    Assembly Version: 2.4.2.0\n    Win32 Version: 2.4.2.0\n    CodeBase: file:///Z:/home/daniel/Games/soapbox-race-world-need-for-speed-world/Flurl.Http.dll\n----------------------------------------\nAnonymously Hosted DynamicMethods Assembly\n    Assembly Version: 0.0.0.0\n    Win32 Version: n/a\n    CodeBase: \n----------------------------------------\nMicrosoft.CSharp\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/Microsoft.CSharp/4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll\n----------------------------------------\nMicrosoft.WindowsAPICodePack.Shell\n    Assembly Version: 1.1.0.0\n    Win32 Version: 1.1.0.0\n    CodeBase: file:///Z:/home/daniel/Games/soapbox-race-world-need-for-speed-world/Microsoft.WindowsAPICodePack.Shell.dll\n----------------------------------------\nMicrosoft.WindowsAPICodePack\n    Assembly Version: 1.1.0.0\n    Win32 Version: 1.1.0.0\n    CodeBase: file:///Z:/home/daniel/Games/soapbox-race-world-need-for-speed-world/Microsoft.WindowsAPICodePack.dll\n----------------------------------------\nPresentationFramework\n    Assembly Version: 3.0.0.0\n    Win32 Version: 3.0.6920.5738 built by: QFE\n    CodeBase: file:///Z:/home/daniel/Games/soapbox-race-world-need-for-speed-world/PresentationFramework.dll\n----------------------------------------\nPresentationCore\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.8.4121.0 built by: NET48REL1LAST_C\n    CodeBase: file:///Z:/home/daniel/Games/soapbox-race-world-need-for-speed-world/PresentationCore.dll\n----------------------------------------\nWindowsBase\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/WindowsBase/4.0.0.0__31bf3856ad364e35/WindowsBase.dll\n----------------------------------------\nSystem.Numerics\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Numerics/4.0.0.0__b77a5c561934e089/System.Numerics.dll\n----------------------------------------\nSystem.Runtime.Serialization\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Runtime.Serialization/4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll\n----------------------------------------\nSystem.Data\n    Assembly Version: 4.0.0.0\n    Win32 Version: 4.6.57.0\n    CodeBase: file:///C:/windows/mono/mono-2.0/lib/mono/gac/System.Data/4.0.0.0__b77a5c561934e089/System.Data.dll\n----------------------------------------\n\n************** JIT Debugging **************\nApplication does not support Windows Forms just-in-time (JIT)\ndebugging. Contact the application author for more\ninformation.\n

**Comment by YannKX** [comment]
How to install AMD drivers on mint? Can you help me ?

**Comment by YannKX** [comment]
Can you open it again?  I accidentally clicke

**Comment by YannKX** [comment]
Czeckpage, I installed lutris and started the game
