### ISSUE TITLE
Distance to escape issue

### ISSUE THREAD

**Issue by catalinstoian16** [SoapboxRaceWorld/GameLauncher_NFSW#72]
- **Launcher Version:** 1.9.1.40
- **Operating system:** Windows 10
- **Antivirus/Firewall (if any):** Windows Defender
- **Wine/Mono Version (if any):** 

**Description of issue:**
```
Every team escape, the distance to escape increases very quickly and then fluctuates if you get busted and then respawn (even though I get closer to the finish line). Also, if I do cross the finish line, the game states that I didn't finish the race.
```

**JIT Error (if any)**
```
none
```
Screenshots:
![nfsw009](https://user-images.githubusercontent.com/30214701/44584426-91aec480-a7b1-11e8-826b-76924001db08.jpg)
![nfsw003](https://user-images.githubusercontent.com/30214701/44584427-91aec480-a7b1-11e8-9157-50f1bf7545b6.jpg)
![nfsw006](https://user-images.githubusercontent.com/30214701/44584428-92475b00-a7b1-11e8-9ed8-c4e6c1a9b9a4.jpg)
![nfsw007](https://user-images.githubusercontent.com/30214701/44584429-92475b00-a7b1-11e8-8e73-54304126584b.jpg)

**Comment by metonator** [comment]
Server related.

**Comment by metonator** [comment]
or @LeoCodes21 🤔

**Comment by ktreus** [comment]
also happened to me but i though was a feature because was happened to me at the first time i played team escape
