### ISSUE TITLE
cant finishing team escase 

### ISSUE THREAD

**Issue by ertu3452** [SoapboxRaceWorld/GameLauncher_NFSW#74]
- **Launcher Version:** 
- **Operating system:** Windows 10 home 64bit
- **Antivirus/Firewall (if any):** no
- **Wine/Mono Version (if any):** no

**Description of issue:**
```when I busted from police on team escape at 1st time I cant finished the escape

I cross the finish line but i can drive after crossing line
Its dont finished
Error description goes here
```

**JIT Error (if any)**
```
Please embed it inside code tag. Otherwise, delete this line or just type "none"
```

**Comment by 1DavidCarbon** [comment]
This issue happens when you get busted during the Team Escape Race. This issue is server side. @LeoCodes21
