### ISSUE TITLE
Launcher won't start the game.

### ISSUE THREAD

**Issue by rjshooter** [SoapboxRaceWorld/GameLauncher_NFSW#76]
- **Launcher Version:** 2.1.3.2
- **Operating system:** Windows 10 Pro
- **Antivirus/Firewall (if any):** Windows Defender
- **Wine/Mono Version (if any):** No

![Untitled](https://user-images.githubusercontent.com/21359767/86123535-e20cb100-bb03-11ea-87e0-9a9d02ff0fe3.png)

The launcher always trying to create a file that already exists, tested on multiple servers.

**Comment by ghost** [comment]
Manually delete .data folder and .links file
