### ISSUE TITLE
Out of Memory

### ISSUE THREAD

**Issue by lev275** [SoapboxRaceWorld/GameLauncher_NFSW#77]
- **Launcher Version: 2.1.3.4** 
- **Operating system: Windows 10** 
- **Antivirus/Firewall (if any): Kaspersky** 
- **Wine/Mono Version (if any): -** 

After i clicked "Play Now", **Critical Error: Out of Memory** always popped up, thus i can't access the game. I've already uninstall the game and install it again, but it still happened.

**Comment by ghost** [comment]
Seems you have kaspersky that locks access via its firewall at this point. Can you check if nfsw.exe process is whitelisted on firewall?

**Comment by Zacam** [comment]
![DisableRPCandProxy](https://user-images.githubusercontent.com/2995385/86522860-f9f07780-be18-11ea-92d3-94daa4f23f8b.png)
Also, have you tried setting the above option in Setting (Gear Icon) in the Launcher?

**Comment by lev275** [comment]
i see, thanks for the help man
