### ISSUE TITLE
ERROR

### ISSUE THREAD

**Issue by Mrlaza893** [SoapboxRaceWorld/GameLauncher_NFSW#78]
- **Launcher Version:** 2.1.3.4.
- **Operating system:** Windows 7 64 bit
- **Antivirus/Firewall (if any):** Firewall
- **Wine/Mono Version (if any):** No
![Picture](https://user-images.githubusercontent.com/67832165/86514544-4d5fc700-be13-11ea-8526-52a924662458.JPG)
This happens when I try to log in to the NightRiderz server, and this after 10 sec
![Picture 1](https://user-images.githubusercontent.com/67832165/86514584-8ac45480-be13-11ea-8343-c4125ded6e11.JPG)

And in the end it can't be install

can you help me please?

**Comment by ghost** [comment]
Please make sure you can fetch those KB from windows update, since many sites forces tls1.2 now (including oir modnet) and windows without those patches are unable to get inside

**Comment by Mrlaza893** [comment]
But when I try to install this happens
![Capture](https://user-images.githubusercontent.com/67832165/86530782-0bd72680-bebc-11ea-9c14-5974f9b08d44.JPG)


Can you give me some link from some video or something else to see what to do since it won't work, and I really like NFS World and I didn't mention that this just happens on the Night Riderz server.
Can you help me please?

**Comment by ghost** [comment]
Use this article posted on devblogs @ microsoft.

https://devblogs.microsoft.com/nuget/deprecating-tls-1-0-and-1-1-on-nuget-org/

niedz., 5 lip 2020, 12:36 użytkownik Mrlaza893 <notifications@github.com>
napisał:
