### ISSUE TITLE
Downloading gamefiles problem

### ISSUE THREAD

**Issue by ghost** [SoapboxRaceWorld/GameLauncher_NFSW#79]
- **Launcher Version:** 2.1.3.5
- **Operating system:** Windows 10
- **Antivirus/Firewall (if any):** Windows Firewall
- **Wine/Mono Version (if any):** 
Hi sir

When I am in the middle of downloading the game files this error shows up and the installation stops. Plz help me my game doesnt download.

![1](https://user-images.githubusercontent.com/67961456/86785158-bf3a4980-c07b-11ea-86d4-acaa42d908f0.png)
![2](https://user-images.githubusercontent.com/67961456/86785163-c19ca380-c07b-11ea-82bf-3468b5e11ada.png)
![3](https://user-images.githubusercontent.com/67961456/86785169-c3666700-c07b-11ea-9843-5597cb3cd0fb.png)

**Comment by ghost** [comment]
Just retry, you probably had internet drop

W dniu wtorek, 7 lipca 2020 mrsimpy <notifications@github.com> napisał(a):

**Comment by ghost** [comment]
I try to retry but it starts from all over again and the same thing happens again

**Comment by hansuned** [comment]
hola a mi me pasa exactamente lo mismo, ayer pase 4 horas seguidas intentando y no lo logre espero que me den respuestas, att: HANSUNED

**Comment by ghost** [comment]
In the middle of the download it stops while my internet connection is still available and then shows the aforementioned errors

![image](https://user-images.githubusercontent.com/67961456/86877506-77113a80-c100-11ea-8066-271c545315ab.png)
