### ISSUE TITLE
SSL Servers are unsupported.

### ISSUE THREAD

**Issue by metonator** [SoapboxRaceWorld/GameLauncher_NFSW#80]
- **Launcher Version:** <= 1.9.3.0-DEVBUILD (Commit: 9779873cb8f62be1860f054159ad6c5369a8a06b) 
- **Operating system:** ANY
- **Antivirus/Firewall (if any):** ---
- **Wine/Mono Version (if any):** ---

**Description of issue:**
SSL seems to be unsupported by Flurl Proxy Handler. `Out of memory` appears

inb4 developer creates issues by its own. coz why the fuck nope? :>

**Comment by redbluescreen** [comment]
Server URLs for testing:
https://sbrw-ssl.nextdata.eu/soapbox-race-core/Engine.svc (Cloudflare SSL)
https://sbrw-ssl-le.nextdata.eu/soapbox-race-core/Engine.svc (Let's Encrypt)

**Comment by metonator** [comment]
Solved as of ac79acd860b50790ded996dd54af6839c4ee874e
