### ISSUE TITLE
cant launch game

### ISSUE THREAD

**Issue by ragexp3** [SoapboxRaceWorld/GameLauncher_NFSW#82]
i just cant launch game after i press "play now" button

**Comment by ghost** [comment]
Need more detailed info, server, os, config, ...

**Comment by snitra** [comment]
when i click on gamelauncher.exe it doesn't even open idk why just last night it was okey need help for this please

**Comment by ragexp3** [comment]
Now the launcher is working fine but it keeps on crashing it's the world
united server

**Comment by snitra** [comment]
the .exe don't respond but i deleted realese file and did another one and selected where i installed game before and it works now if anyone stuck on it

**Comment by snitra** [comment]
![image](https://user-images.githubusercontent.com/68605885/88258785-d8b4d580-ccb8-11ea-8fb7-579ea8e21021.png) now i got this error bruh from error to another one
