### ISSUE TITLE
My launcher has hordes of problems

### ISSUE THREAD

**Issue by nfsplyr** [SoapboxRaceWorld/GameLauncher_NFSW#84]
- **Launcher Version:2.1.3.8** 
- **Operating system:windows 10** 
- **Antivirus/Firewall (if any):windows firewall+avira antivirus**
hi,i wanted to report this issue:
so i downloaded gamelauncher reborn 2.1.3.8 about a week ago,and i went throughout the whole process,and it went normal,but when it got to downloading track(high)files,things started to happen...
first,after it downloaded 3MB of the files,i got this message:
![20200729_102224](https://user-images.githubusercontent.com/68984570/88884414-cb18c600-d24b-11ea-8dfa-3fa3f4587fa0.jpg)
Then,a second later,i got this:
![20200729_091732](https://user-images.githubusercontent.com/68984570/88884501-fe5b5500-d24b-11ea-987c-fa6fe46f4143.jpg)
then i restarted the launcher,and to my surprise,it said it was ready,i didnt think much of it,and just logged into a server,the server loaded for a short time and then,i got this:
![20200729_111559](https://user-images.githubusercontent.com/68984570/88884720-70cc3500-d24c-11ea-9b97-d4715cfbba3d.jpg)
And again,a second later,i got this:
![20200729_111617](https://user-images.githubusercontent.com/68984570/88884806-98bb9880-d24c-11ea-80b5-e056b177c2a7.jpg)
I tried deleting and redownloading it many times,but nothing worked,so id be more than happy if you could give a guide as to how to fix this🙂

**Comment by SkyWaii** [comment]
I've tried the same as @nfsplyr actually. I run it under Windows **10** , version **2.1.3.8** .

My treasure hunt will reset today noooOoooOOOooOOoo :( ^^"

![1](https://user-images.githubusercontent.com/69006692/88944486-143d3a00-d28d-11ea-8eef-8875dfb2fe3f.PNG)
![2](https://user-images.githubusercontent.com/69006692/88944496-17382a80-d28d-11ea-9b4f-a8190eb2d6d2.PNG)

**Comment by SkyWaii** [comment]
Hello again!

Even after I downloaded updates for the game, I still have the errors .. :c
![1](https://user-images.githubusercontent.com/69006692/89122989-3670cb00-d4cc-11ea-945a-1b6066b06940.PNG)
![2](https://user-images.githubusercontent.com/69006692/89122993-396bbb80-d4cc-11ea-947c-553810b24de3.PNG)

Just giving some news about it ^^"

**Comment by riomccloud** [comment]
Here's the same. I'm attaching the log files.
[SBRCrashDump_CL0_2020.08.06_17.18.50.txt](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/5036670/SBRCrashDump_CL0_2020.08.06_17.18.50.txt)

**Comment by Zacam** [comment]
GameLauncher.exe and nfsw.exe should not both be in the same folder directly with each other.
Recommend: 1 "Main" folder that houses "Launcher" folder and "GameFiles" folder, so to have them separate but easily contained in one location.
EG:
C:\Soapbox Race World (Or on D: or any other drive letter)
|    \Soapbox Launcher  (Launcher files from Release zip here)
|    \Need For Speed World (or Game Files) (nfsw.exe and game folders\files here)

**Comment by riomccloud** [comment]
> 
> 
> GameLauncher.exe and nfsw.exe should not both be in the same folder directly with each other.
> Recommend: 1 "Main" folder that houses "Launcher" folder and "GameFiles" folder, so to have them separate but easily contained in one location.
> EG:
> C:\Soapbox Race World (Or on D: or any other drive letter)
> | \Soapbox Launcher (Launcher files from Release zip here)
> | \Need For Speed World (or Game Files) (nfsw.exe and game folders\files here)

The same error still happens. Nothing changed.

**Comment by nfsplyr** [comment]
My past issues got fixed but now im getting this:
![20200826_202022](https://user-images.githubusercontent.com/68984570/91326734-edb1e680-e7d9-11ea-9e38-55a5f96fe3b6.jpg)
Even though my version is 2.1.3.8 and i know youre trying to deal with inconsistencies in regards to cdn problems and thats respectable,but pls inform me if i can fix this manually in any way
thank you🙂

**Comment by ghost** [comment]
This issue with cdn down should be fixed now

**Comment by nfsplyr** [comment]
> This issue with cdn down should be fixed now

tnk,i really appreciate it,also from what i could comprehend,one major obstecale keeping me from launching the game was having a PAP internet connection,which should be fixed by now,again thank you for the effort🙂
