### ISSUE TITLE
Problem with the game

### ISSUE THREAD

**Issue by ksinfer** [SoapboxRaceWorld/GameLauncher_NFSW#89]
- **Launcher Version:** 2.1.5.0
- **Operating system:**  Win 10
- **Antivirus/Firewall (if any):** Win defender (turned off)
- **Wine/Mono Version (if any):** 

-access error 0x5
-The process nfsw.exe was killed by task manager
-Critical error (Sbrcrashdump error)
-ModNet files download error
I tried to re download the game but then this error occured
-Unhandled exepcion has occured in your app. If u click countinue the application will ignore this error and attempt to continue. (after clicking the continue button nothing happens, and when i close it manually it frezzes at the same moment when i try to download the game)
I would really aprecciate some help. I love this game recklessly, so if anyone could help me I'd be grateful

**Comment by Zacam** [comment]
1: Launcher should always be run "As Administrator"
2: Use version 2.1.3.8 until ModNet file download errors are fixed, or clear the MODS folder contents to get fresh versions downloaded
3: Make sure GameLauncher.exe and nflsw.exe are in separate folders from each other and not in the same folder directly with each other.
