### ISSUE TITLE
GameLauncher 2.0.2.4 LZMA.ddl Missing

### ISSUE THREAD

**Issue by DavidCarbon** [SoapboxRaceWorld/GameLauncher_NFSW#9]
- **Launcher Version:** 2.0.2.4
- **Operating system:** Windows 10 Pro

So.... looks like it happened again.... yea....

**Comment by DavidCarbon** [comment]
Well it *is* a prelease :)

**Comment by DavidCarbon** [comment]
- **Launcher Version:** 2.0.2.4
- **Operating system:** Windows 10 Pro

I also found that launching the game launcher with no antius and having created multiple exceptions for the application causes the launcher to display "Failed to connect to internet." Its able to check version and download the game files from cdn

**Comment by RedTheKitsune** [comment]
I think this is actually related to Nancy package update I made in the past releases.
Hmm I think its better to put LZMA.dll in server and download it at runtime or put it in folder and copy it automatically after compilation. Its better to make this things automatically than copy it manually, someone can forget about copying ;)

**Comment by RedTheKitsune** [comment]
I included LZMA.dll downloader in last release but it still didn't fix error related to user login. And I need to revert packages to 2.0.2.2 launcher version. (We thinked that was Nancy fault but well its not :( )

**Comment by DavidCarbon** [comment]
Hmmm, Interesting. Well I suggest to blacklist the new versions on the Game Launcher detecting a new version since my users just simply click update and get stuck with the buggy version.

**Comment by RedTheKitsune** [comment]
So I compiled launcher with reverted packages, send it to google drive and posted link to it on WOPL discord. From what people say it actually fixes the bug so thats good. I pushed fix to repo. Now we only need to wait for official release.

**Comment by ghost** [comment]
Issue solved once and for all... forever
