### ISSUE TITLE
NFS World opens and crashes after

### ISSUE THREAD

**Issue by riomccloud** [SoapboxRaceWorld/GameLauncher_NFSW#92]
- **Launcher Version:** 2.1.3.8
- **Operating system:** Windows 10 Home build 2004
- **Antivirus/Firewall (if any):** Kaspersky Security Cloud Free
- **Wine/Mono Version (if any):** 

The game opens, starts loading and crashes.
Here's the log:
[SBRCrashDump_CL0_2020.08.06_17.18.50.txt](https://github.com/SoapboxRaceWorld/GameLauncher_NFSW/files/5078010/SBRCrashDump_CL0_2020.08.06_17.18.50.txt)

**Comment by ghost** [comment]
cc: @LeoCodes21

**Comment by ppmontei** [comment]
I've got the same error, @LeoCodes21
