### ISSUE TITLE
I enter to the game, i play 1minute and the game crash...

### ISSUE THREAD

**Issue by Waazyy1** [SoapboxRaceWorld/GameLauncher_NFSW#93]
- **GAMEEEEEEEEEE:** 

I enter to the game, i play 1minute and the game crash...
https://prnt.sc/u06wmo
![Screenshot_1](https://user-images.githubusercontent.com/69732974/90320474-a99d2700-df39-11ea-8cfe-b2f5497495e2.png)

**Comment by ghost** [comment]
Not a launcher issue. Closing.
