### ISSUE TITLE
nfsw.exe is modified. no it isnt

### ISSUE THREAD

**Issue by PsyK0** [SoapboxRaceWorld/GameLauncher_NFSW#95]
- **Launcher Version:** 2.1.3.8
- **Operating system:** windows 7
- **Antivirus/Firewall (if any):** windows firewall
- **Wine/Mono Version (if any):** 
![nfsw](https://user-images.githubusercontent.com/70527976/91733210-d872f880-ebdb-11ea-884a-0be2af5c39a2.PNG)

**Comment by PsyK0** [comment]
how to fix this?

**Comment by ghost** [comment]
replace with http://cdn.worldunited.gg/gamefiles/unpacked/nfsw.exe one

**Comment by PsyK0** [comment]
it still doesnt work

**Comment by PsyK0** [comment]
how to fix dis?

**Comment by Zicker99** [comment]
i have same issue here

**Comment by Zicker99** [comment]
Even i downloaded game files via launcher still giving same error message

**Comment by ghost** [comment]
For sure y'all have modified executable... just make sure its correct by
providing me SHA1 of the file :P

**Comment by Zacam** [comment]
If it says the nfsw.exe is modified, that's because it's either modified, or failing to pass validation (due to perhaps improper download caused by network or wireless).
If the nfsw.exe was fine, then it would not be giving that message.
