### ISSUE TITLE
GameLauncher not working on Windows 7 Home Premium

### ISSUE THREAD

**Issue by VMadureira** [SoapboxRaceWorld/GameLauncher_NFSW#96]
- **Launcher Version:** 2.1.3.8
- **Operating system:** Windows 7 Home Premium
- **Antivirus/Firewall (if any):** Panda Dome
- **Wine/Mono Version (if any):**

**Comment by VMadureira** [comment]
I press on GameLauncher in Administrator and nothing happens.
On windows task manager in Processes the GameLauncher disappears after some time.
I disable the anti virus a while and the same happen again.

**Comment by VMadureira** [comment]
Launcher - Text file created by GameLauncher before it stops working

[DEBUG] GameLauncher 2.1.3.8
[DEBUG] Setting up current directory: C:\Users\Madvik\Downloads\NFSW\Launcher
[DEBUG] Checking current directory
[DEBUG] Starting GameLauncherUpdater downloader
[URL] Calling URL: https://files.worldunited.gg/GameLauncherUpdater.exe
[DEBUG] Checking Proxy
[DEBUG] Starting MainScreen
[DEBUG] Entered mainScreen
[DEBUG] Setting SSL Protocol
[DEBUG] Detecting OS
[DEBUG] Detected OS: Windows 7 Home Premium
[DEBUG] OS Details: Microsoft Windows NT 6.1.7601 Service Pack 1
[DEBUG] Video Card: NVIDIA GeForce GTX 1050
[DEBUG] Driver Version: 27.21.14.5206
[DEBUG] InitializeComponent

**Comment by Zacam** [comment]
You can't just "disable" the anti-virus; you have to make exclusions/exceptions to allow applications/programs through.
Especially for a non-publisher 'certified' game (and one with an installer to boot), having AV disabled means an application like the launcher can't even request permission ... it has nothing to talk to.
