### ISSUE TITLE
Need For Speed Invalid Comand Line

### ISSUE THREAD

**Issue by Samueul** [SoapboxRaceWorld/GameLauncher_NFSW#98]
- **Launcher Version:** 2.1.3.8
![Captura de Tela (10)](https://user-images.githubusercontent.com/72715828/95694940-03a12c80-0c0b-11eb-8ba9-2b261fac32b5.png)

- **Operating system:** 
- **Antivirus/Firewall (if any):** 
- **Wine/Mono Version (if any):**

**Comment by Zacam** [comment]
That usually only happens when there is a corrupted setup or game files problem.

**Comment by Samueul** [comment]
how do I fix @Zacam ?
